///@description KSW - Set Fishes

function scr_KSW_SetFishes()
{
	#region Setup
	global.KSW_FishCount = 0;
	
	global.KSW_FishList = [];
	global.KSW_FishIDs = ds_map_create();
	#endregion
	
	#region Stages
	var anyStage = -1;
	var grassBeach = global.KSW_StageIDs[? "grassBeach"];
	var creamCrevasse = global.KSW_StageIDs[? "creamCrevasse"];
	var hallowReen = global.KSW_StageIDs[? "hallowReen"];
	#endregion
	
	#region Caught Box Palettes
	var candy = spr_KSW_UI_CaughtBox_Palette_Candy;
	var mint = spr_KSW_UI_CaughtBox_Palette_Mint;
	var legion = spr_KSW_UI_CaughtBox_Palette_Legion;
	var mage = spr_KSW_UI_CaughtBox_Palette_Mage;
	var glimmer = spr_KSW_UI_CaughtBox_Palette_Glimmer;
	var borange = spr_KSW_UI_CaughtBox_Palette_Borange;
	var flux = spr_KSW_UI_CaughtBox_Palette_Flux;
	var maze = spr_KSW_UI_CaughtBox_Palette_Maze;
	var tvtime = spr_KSW_UI_CaughtBox_Palette_TVTime;
	#endregion
	
	#region Add Fishes Here
	#region 1.0
	scr_KSW_AddFish("Blipper","Kirby",spr_KSW_Fish_Blipper,spr_KSW_Fish_Blipper_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,500);
	scr_KSW_AddFish("Slippy","Kirby",spr_KSW_Fish_Slippy,spr_KSW_Fish_Slippy_Pal_Normal,borange,0,grassBeach,KSW_Phases.day,400);
	scr_KSW_AddFish("Glunk","Kirby",spr_KSW_Fish_Glunk,spr_KSW_Fish_Glunk_Pal_Normal,mint,0,grassBeach,KSW_Phases.day,450);
	scr_KSW_AddFish("Diving Gordo","Kirby",spr_KSW_Fish_DivingGordo,spr_KSW_Fish_DivingGordo_Pal_Normal,flux,1,grassBeach,KSW_Phases.day,800);
	scr_KSW_AddFish("Leap","Kirby",spr_KSW_Fish_Leap,spr_KSW_Fish_Leap_Pal_Normal,mage,0,grassBeach,KSW_Phases.day,300);
	scr_KSW_AddFish("Gusso","Kirby",spr_KSW_Fish_Gusso,spr_KSW_Fish_Gusso_Pal_Normal,mage,0,grassBeach,KSW_Phases.afternoon,600,-3,0);
	scr_KSW_AddFish("Joe","Kirby",spr_KSW_Fish_Joe,spr_KSW_Fish_Joe_Pal_Normal,mage,0,grassBeach,KSW_Phases.night,2000,-2,1);
	scr_KSW_AddFish("Pacto","Kirby",spr_KSW_Fish_Pacto,spr_KSW_Fish_Pacto_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.night,2500,0,-2);
	scr_KSW_AddFish("Squishy","Kirby",spr_KSW_Fish_Squishy,spr_KSW_Fish_Squishy_Pal_Normal,mage,0,grassBeach,KSW_Phases.afternoon,1000);
	scr_KSW_AddFish("Flotzo","Kirby",spr_KSW_Fish_Flotzo,spr_KSW_Fish_Flotzo_Pal_Normal,candy,0,grassBeach,KSW_Phases.afternoon,1500);
	scr_KSW_AddFish("Peezer","Kirby",spr_KSW_Fish_Peezer,spr_KSW_Fish_Peezer_Pal_Normal,mage,0,grassBeach,KSW_Phases.afternoon,400,0,1);
	scr_KSW_AddFish("Tortletummy","Kirby",spr_KSW_Fish_Tortletummy,spr_KSW_Fish_Tortletummy_Pal_Normal,mint,2,grassBeach,KSW_Phases.afternoon,15000,10,30);
	scr_KSW_AddFish("Stickle","Kirby",spr_KSW_Fish_Stickle,spr_KSW_Fish_Stickle_Pal_Normal,legion,0,grassBeach,KSW_Phases.afternoon,750);
	scr_KSW_AddFish("Squister","Kirby",spr_KSW_Fish_Squister,spr_KSW_Fish_Squister_Pal_Normal,mage,0,grassBeach,KSW_Phases.afternoon,1000);
	scr_KSW_AddFish("Slugoo","Kirby",spr_KSW_Fish_Slugoo,spr_KSW_Fish_Slugoo_Pal_Normal,mint,0,grassBeach,KSW_Phases.day,3000);
	scr_KSW_AddFish("Elebli","Kirby",spr_KSW_Fish_Elebli,spr_KSW_Fish_Elebli_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.night,500,-3,0);
	scr_KSW_AddFish("Blish","Kirby",spr_KSW_Fish_Blish,spr_KSW_Fish_Blish_Pal_Normal,mint,0,grassBeach,KSW_Phases.day,15000,-16);
	scr_KSW_AddFish("King Eelongo","Kirby",spr_KSW_Fish_KingEelongo,spr_KSW_Fish_KingEelongo_Pal_Normal,borange,3,grassBeach,KSW_Phases.night,60000,-175,24);
	scr_KSW_AddFish("Acro","Kirby",spr_KSW_Fish_Acro,spr_KSW_Fish_Acro_Pal_Normal,legion,2,grassBeach,KSW_Phases.night,30000,-19,0);
	scr_KSW_AddFish("Fatty Whale","Kirby",spr_KSW_Fish_FattyWhale,spr_KSW_Fish_FattyWhale_Pal_Normal,mage,3,grassBeach,KSW_Phases.afternoon,50000,-32,10);
	scr_KSW_AddFish("Mini Gobbler","Kirby",spr_KSW_Fish_MiniGobbler,spr_KSW_Fish_MiniGobbler_Pal_Normal,candy,0,grassBeach,KSW_Phases.night,800);
	scr_KSW_AddFish("Gobbler","Kirby",spr_KSW_Fish_Gobbler,spr_KSW_Fish_Gobbler_Pal_Normal,mage,2,grassBeach,KSW_Phases.night,20000,-12,2);
	scr_KSW_AddFish("Kine","Kirby",spr_KSW_Fish_Kine,spr_KSW_Fish_Kine_Pal_Normal,mage,1,grassBeach,KSW_Phases.day,7500,-4);
	scr_KSW_AddFish("Merman","Castlevania",spr_KSW_Fish_Merman,spr_KSW_Fish_Merman_Pal_Normal,borange,1,hallowReen,KSW_Phases.none,2000,2,12);
	scr_KSW_AddFish("Giant Merman","Castlevania",spr_KSW_Fish_GiantMerman,spr_KSW_Fish_GiantMerman_Pal_Normal,mint,2,hallowReen,KSW_Phases.none,10000,-10,14);
	scr_KSW_AddFish("Fish Head","Castlevania",spr_KSW_Fish_FishHead,spr_KSW_Fish_FishHead_Pal_Normal,legion,1,hallowReen,KSW_Phases.none,3000,-10,14);
	scr_KSW_AddFish("Peeping Eye","Castlevania",spr_KSW_Fish_PeepingEye,spr_KSW_Fish_PeepingEye_Pal_Normal,borange,2,hallowReen,KSW_Phases.none,6000,0,16);
	scr_KSW_AddFish("Peeping Big","Castlevania",spr_KSW_Fish_PeepingBig,spr_KSW_Fish_PeepingBig_Pal_Normal,borange,3,hallowReen,KSW_Phases.none,14000,-1,18);
	scr_KSW_AddFish("Metroid","Metroid",spr_KSW_Fish_Metroid,spr_KSW_Fish_Metroid_Pal_Normal,mint,1,grassBeach,KSW_Phases.afternoon,2500);
	scr_KSW_AddFish("Skultera","Metroid",spr_KSW_Fish_Skultera,spr_KSW_Fish_Skultera_Pal_Normal,flux,0,grassBeach,KSW_Phases.night,1000,-8,-4);
	scr_KSW_AddFish("Evir","Metroid",spr_KSW_Fish_Evir,spr_KSW_Fish_Evir_Pal_Normal,borange,0,grassBeach,KSW_Phases.afternoon,900,-4,8);
	scr_KSW_AddFish("Draygon","Metroid",spr_KSW_Fish_Draygon,spr_KSW_Fish_Draygon_Pal_Normal,mint,2,grassBeach,KSW_Phases.afternoon,30000,-30,36);
	scr_KSW_AddFish("Phantoon","Metroid",spr_KSW_Fish_Phantoon,spr_KSW_Fish_Phantoon_Pal_Normal,mint,2,grassBeach,KSW_Phases.night,20000,0,-16);
	scr_KSW_AddFish("Botwoon","Metroid",spr_KSW_Fish_Botwoon,spr_KSW_Fish_Botwoon_Pal_Normal,borange,1,grassBeach,KSW_Phases.night,10000,-44,30);
	scr_KSW_AddFish("Serris","Metroid",spr_KSW_Fish_Serris,spr_KSW_Fish_Serris_Pal_Normal,mint,2,grassBeach,KSW_Phases.afternoon,40000,-86,-8);
	scr_KSW_AddFish("Guppy","Insaniquarium",spr_KSW_Fish_Guppy,spr_KSW_Fish_Guppy_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,500,0,0,-1,snd_KSW_Fish_Guppy);
	scr_KSW_AddFish("Carnivore","Insaniquarium",spr_KSW_Fish_Carnivore,spr_KSW_Fish_Carnivore_Pal_Normal,legion,0,grassBeach,KSW_Phases.day,750,-1,3);
	scr_KSW_AddFish("Starcatcher","Insaniquarium",spr_KSW_Fish_Starcatcher,spr_KSW_Fish_Starcatcher_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.afternoon,750);
	scr_KSW_AddFish("Fecal Forgo","Slayers X",spr_KSW_Fish_FecalForgo,spr_KSW_Fish_FecalForgo_Pal_Normal,mint,3,grassBeach,KSW_Phases.day,100000,0,0,-1,snd_KSW_Fish_FecalFunny);
	scr_KSW_AddFish("Red Cheep Cheep","Mario",spr_KSW_Fish_CheepCheepRed,spr_KSW_Fish_CheepCheepRed_Pal_Normal,candy,0,grassBeach,KSW_Phases.afternoon,400);
	scr_KSW_AddFish("Green Cheep Cheep","Mario",spr_KSW_Fish_CheepCheepGreen,spr_KSW_Fish_CheepCheepGreen_Pal_Normal,mint,0,grassBeach,KSW_Phases.day,400);
	scr_KSW_AddFish("Blooper","Mario",spr_KSW_Fish_Blooper,spr_KSW_Fish_Blooper_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.day,1000);
	scr_KSW_AddFish("Bloopad","Mario",spr_KSW_Fish_Bloopad,spr_KSW_Fish_Bloopad_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.day,1000);
	scr_KSW_AddFish("Blurp","Mario",spr_KSW_Fish_Blurp,spr_KSW_Fish_Blurp_Pal_Normal,mint,0,grassBeach,KSW_Phases.day,600);
	scr_KSW_AddFish("Rip Van Fish","Mario",spr_KSW_Fish_RipVanFish,spr_KSW_Fish_RipVanFish_Pal_Normal,flux,0,grassBeach,KSW_Phases.day,800);
	scr_KSW_AddFish("Fish Bone","Mario",spr_KSW_Fish_FishBone,spr_KSW_Fish_FishBone_Pal_Normal,legion,1,hallowReen,KSW_Phases.none,1200,-2,0);
	scr_KSW_AddFish("Morton","Mario",spr_KSW_Fish_Morton,spr_KSW_Fish_Morton_Pal_Normal,mage,3,grassBeach,KSW_Phases.afternoon,30000,-2,2);
	scr_KSW_AddFish("Sonic the Fish","Sonic",spr_KSW_Fish_SonicFish,spr_KSW_Fish_SonicFish_Pal_Normal,legion,3,grassBeach,KSW_Phases.day,30000,-38,-16);
	scr_KSW_AddFish("Eggman","Sonic",spr_KSW_Fish_Eggman,spr_KSW_Fish_Eggman_Pal_Normal,flux,3,grassBeach,KSW_Phases.night,30000,-8,10);
	scr_KSW_AddFish("Ring","Sonic",spr_KSW_Fish_Ring,spr_KSW_Fish_Ring_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.day,2500,-8,-8);
	scr_KSW_AddFish("Star Post","Sonic",spr_KSW_Fish_StarPost,spr_KSW_Fish_StarPost_Pal_Normal,legion,2,grassBeach,KSW_Phases.afternoon,4250,-8,-16);
	scr_KSW_AddFish("Goal Plate","Sonic",spr_KSW_Fish_GoalPlate,spr_KSW_Fish_GoalPlate_Pal_Normal,candy,2,grassBeach,KSW_Phases.afternoon,8500,-20,-16);
	scr_KSW_AddFish("Item Box","Sonic",spr_KSW_Fish_ItemBox,spr_KSW_Fish_ItemBox_Pal_Normal,mage,1,grassBeach,KSW_Phases.night,4000,-15,-12);
	scr_KSW_AddFish("Spring","Sonic",spr_KSW_Fish_Spring,spr_KSW_Fish_Spring_Pal_Normal,candy,0,grassBeach,KSW_Phases.night,500,-16,-20);
	scr_KSW_AddFish("Chopper","Sonic",spr_KSW_Fish_Chopper,spr_KSW_Fish_Chopper_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,2000,-8,-1);
	scr_KSW_AddFish("Crabmeat","Sonic",spr_KSW_Fish_Crabmeat,spr_KSW_Fish_Crabmeat_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,3000,0,4);
	scr_KSW_AddFish("Masher","Sonic",spr_KSW_Fish_Masher,spr_KSW_Fish_Masher_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,1500,-6,2);
	scr_KSW_AddFish("Chop Chop","Sonic",spr_KSW_Fish_ChopChop,spr_KSW_Fish_ChopChop_Pal_Normal,legion,0,grassBeach,KSW_Phases.afternoon,1000,-4,0);
	scr_KSW_AddFish("Aquis","Sonic",spr_KSW_Fish_Aquis,spr_KSW_Fish_Aquis_Pal_Normal,mint,1,grassBeach,KSW_Phases.afternoon,2500,-2,12);
	scr_KSW_AddFish("Shellcracker","Sonic",spr_KSW_Fish_Shellcracker,spr_KSW_Fish_Shellcracker_Pal_Normal,candy,1,grassBeach,KSW_Phases.afternoon,5000);
	scr_KSW_AddFish("Asteron","Sonic",spr_KSW_Fish_Asteron,spr_KSW_Fish_Asteron_Pal_Normal,borange,0,grassBeach,KSW_Phases.afternoon,2000);
	scr_KSW_AddFish("Turtloid","Sonic",spr_KSW_Fish_Turtloid,spr_KSW_Fish_Turtloid_Pal_Normal,mint,2,grassBeach,KSW_Phases.afternoon,8000,-24,-12);
	scr_KSW_AddFish("Pointdexter","Sonic",spr_KSW_Fish_Pointdexter,spr_KSW_Fish_Pointdexter_Pal_Normal,legion,1,grassBeach,KSW_Phases.night,4000,-6,2);
	scr_KSW_AddFish("Turbo Spiker","Sonic",spr_KSW_Fish_TurboSpiker,spr_KSW_Fish_TurboSpiker_Pal_Normal,candy,1,grassBeach,KSW_Phases.afternoon,4500,-8,-2);
	scr_KSW_AddFish("Mega Chopper","Sonic",spr_KSW_Fish_MegaChopper,spr_KSW_Fish_MegaChopper_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,800,-2,0);
	scr_KSW_AddFish("Jawz","Sonic",spr_KSW_Fish_Jawz,spr_KSW_Fish_Jawz_Pal_Normal,mage,1,grassBeach,KSW_Phases.night,2500,-18,0);
	scr_KSW_AddFish("Doshin","Doshin the Giant",spr_KSW_Fish_Doshin,spr_KSW_Fish_Doshin_Pal_Normal,borange,3,grassBeach,KSW_Phases.day,90000,9,218);
	scr_KSW_AddFish("Bloppo The Warbler","",spr_KSW_Fish_Bloppo,spr_KSW_Fish_Bloppo_Pal_Normal,candy,3,grassBeach,KSW_Phases.afternoon,60000,2,60,-1,snd_KSW_Fish_Bloppo);
	scr_KSW_AddFish("Octorok","Zelda",spr_KSW_Fish_Octorok,spr_KSW_Fish_Octorok_Pal_Normal,candy,0,grassBeach,KSW_Phases.afternoon,3000,1,0);
	scr_KSW_AddFish("Big Octorok","Zelda",spr_KSW_Fish_BigOctorok,spr_KSW_Fish_BigOctorok_Pal_Normal,candy,1,grassBeach,KSW_Phases.afternoon,12000,-30,0);
	scr_KSW_AddFish("Chuchu","Zelda",spr_KSW_Fish_Chuchu,spr_KSW_Fish_Chuchu_Pal_Normal,legion,0,grassBeach,KSW_Phases.day,2500);
	scr_KSW_AddFish("Big Chuchu","Zelda",spr_KSW_Fish_BigChuchu,spr_KSW_Fish_BigChuchu_Pal_Normal,legion,1,grassBeach,KSW_Phases.day,14000,0,14);
	scr_KSW_AddFish("Sluggula","Zelda",spr_KSW_Fish_Sluggula,spr_KSW_Fish_Sluggula_Pal_Normal,legion,0,grassBeach,KSW_Phases.day,1500);
	scr_KSW_AddFish("Cloud Piranha","Zelda",spr_KSW_Fish_CloudPiranha,spr_KSW_Fish_CloudPiranha_Pal_Normal,legion,0,grassBeach,KSW_Phases.afternoon,1000,-1,-2);
	scr_KSW_AddFish("Zora","Zelda",spr_KSW_Fish_Zora,spr_KSW_Fish_Zora_Pal_Normal,mint,1,grassBeach,KSW_Phases.night,5000,0,-1);
	scr_KSW_AddFish("Ganondorf","Zelda",spr_KSW_Fish_Ganondorf,spr_KSW_Fish_Ganondorf_Pal_Normal,mage,3,grassBeach,KSW_Phases.night,60000,-6,36);
	scr_KSW_AddFish("Atlantic Cod","Terraria",spr_KSW_Fish_AtlanticCod,spr_KSW_Fish_AtlanticCod_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,870);
	scr_KSW_AddFish("Neon Tetra","Terraria",spr_KSW_Fish_NeonTetra,spr_KSW_Fish_NeonTetra_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,90);
	scr_KSW_AddFish("Red Snapper","Terraria",spr_KSW_Fish_RedSnapper,spr_KSW_Fish_RedSnapper_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,820);
	scr_KSW_AddFish("Tuna","Terraria",spr_KSW_Fish_Tuna,spr_KSW_Fish_Tuna_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,980);
	scr_KSW_AddFish("Salmon","Terraria",spr_KSW_Fish_Salmon,spr_KSW_Fish_Salmon_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,1100);
	scr_KSW_AddFish("Bass","Terraria",spr_KSW_Fish_Bass,spr_KSW_Fish_Bass_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,740);
	scr_KSW_AddFish("Flounder","Terraria",spr_KSW_Fish_Flounder,spr_KSW_Fish_Flounder_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,690);
	scr_KSW_AddFish("Rock Lobster","Terraria",spr_KSW_Fish_RockLobster,spr_KSW_Fish_RockLobster_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,920);
	scr_KSW_AddFish("Trout","Terraria",spr_KSW_Fish_Trout,spr_KSW_Fish_Trout_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,800);
	scr_KSW_AddFish("Shrimp","Terraria",spr_KSW_Fish_Shrimp,spr_KSW_Fish_Shrimp_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Crimson Tigerfish","Terraria",spr_KSW_Fish_CrimsonTigerfish,spr_KSW_Fish_CrimsonTigerfish_Pal_Normal,candy,1,grassBeach,KSW_Phases.none,970);
	scr_KSW_AddFish("Specular Fish","Terraria",spr_KSW_Fish_SpecularFish,spr_KSW_Fish_SpecularFish_Pal_Normal,legion,1,grassBeach,KSW_Phases.none,1300);
	scr_KSW_AddFish("Blue Jellyfish (Bait)","Terraria",spr_KSW_Fish_BlueJellyfishBait,spr_KSW_Fish_BlueJellyfishBait_Pal_Normal,legion,1,grassBeach,KSW_Phases.none,230);
	scr_KSW_AddFish("Green Jellyfish (Bait)","Terraria",spr_KSW_Fish_GreenJellyfishBait,spr_KSW_Fish_GreenJellyfishBait_Pal_Normal,mint,1,grassBeach,KSW_Phases.none,250);
	scr_KSW_AddFish("Pink Jellyfish (Bait)","Terraria",spr_KSW_Fish_PinkJellyfishBait,spr_KSW_Fish_PinkJellyfishBait_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.none,270);
	scr_KSW_AddFish("Stinkfish","Terraria",spr_KSW_Fish_Stinkfish,spr_KSW_Fish_Stinkfish_Pal_Normal,mint,1,grassBeach,KSW_Phases.none,470);
	scr_KSW_AddFish("Armored Cavefish","Terraria",spr_KSW_Fish_ArmoredCavefish,spr_KSW_Fish_ArmoredCavefish_Pal_Normal,flux,1,grassBeach,KSW_Phases.none,3400);
	scr_KSW_AddFish("Damselfish","Terraria",spr_KSW_Fish_Damselfish,spr_KSW_Fish_Damselfish_Pal_Normal,mage,1,grassBeach,KSW_Phases.none,880);
	scr_KSW_AddFish("Double Cod","Terraria",spr_KSW_Fish_DoubleCod,spr_KSW_Fish_DoubleCod_Pal_Normal,mint,1,grassBeach,KSW_Phases.none,1600);
	scr_KSW_AddFish("Ebonkoi","Terraria",spr_KSW_Fish_Ebonkoi,spr_KSW_Fish_Ebonkoi_Pal_Normal,flux,1,grassBeach,KSW_Phases.none,1700);
	scr_KSW_AddFish("Frost Minnow","Terraria",spr_KSW_Fish_FrostMinnow,spr_KSW_Fish_FrostMinnow_Pal_Normal,legion,1,creamCrevasse,KSW_Phases.none,360);
	scr_KSW_AddFish("Hemopiranha","Terraria",spr_KSW_Fish_Hemopiranha,spr_KSW_Fish_Hemopiranha_Pal_Normal,candy,1,grassBeach,KSW_Phases.none,520);
	scr_KSW_AddFish("Honeyfin","Terraria",spr_KSW_Fish_Honeyfin,spr_KSW_Fish_Honeyfin_Pal_Normal,borange,1,grassBeach,KSW_Phases.none,1200);
	scr_KSW_AddFish("Variegated Lardfish","Terraria",spr_KSW_Fish_VariegatedLardfish,spr_KSW_Fish_VariegatedLardfish_Pal_Normal,mage,1,grassBeach,KSW_Phases.none,7400);
	scr_KSW_AddFish("Obsidifish","Terraria",spr_KSW_Fish_Obsidifish,spr_KSW_Fish_Obsidifish_Pal_Normal,flux,2,grassBeach,KSW_Phases.none,2900);
	scr_KSW_AddFish("Princess Fish","Terraria",spr_KSW_Fish_PrincessFish,spr_KSW_Fish_PrincessFish_Pal_Normal,flux,2,grassBeach,KSW_Phases.none,3300);
	scr_KSW_AddFish("Flarefin Koi","Terraria",spr_KSW_Fish_FlarefinKoi,spr_KSW_Fish_FlarefinKoi_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,4000);
	scr_KSW_AddFish("Prismite","Terraria",spr_KSW_Fish_Prismite,spr_KSW_Fish_Prismite_Pal_Normal,flux,2,grassBeach,KSW_Phases.none,4400);
	scr_KSW_AddFish("Golden Carp","Terraria",spr_KSW_Fish_GoldenCarp,spr_KSW_Fish_GoldenCarp_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,5000);
	scr_KSW_AddFish("Chaos Fish","Terraria",spr_KSW_Fish_ChaosFish,spr_KSW_Fish_ChaosFish_Pal_Normal,flux,2,grassBeach,KSW_Phases.none,4200);
	scr_KSW_AddFish("Amanita Fungifin","Terraria",spr_KSW_Fish_AmanitaFungifin,spr_KSW_Fish_AmanitaFungifin_Pal_Normal,mage,3,grassBeach,KSW_Phases.none,6900);
	scr_KSW_AddFish("Angelfish","Terraria",spr_KSW_Fish_Angelfish,spr_KSW_Fish_Angelfish_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,3600);
	scr_KSW_AddFish("Batfish","Terraria",spr_KSW_Fish_Batfish,spr_KSW_Fish_Batfish_Pal_Normal,legion,3,grassBeach,KSW_Phases.none,1800);
	scr_KSW_AddFish("Bloody Manowar","Terraria",spr_KSW_Fish_BloodyManowar,spr_KSW_Fish_BloodyManowar_Pal_Normal,candy,3,grassBeach,KSW_Phases.none,3900);
	scr_KSW_AddFish("Bonefish","Terraria",spr_KSW_Fish_Bonefish,spr_KSW_Fish_Bonefish_Pal_Normal,mint,3,grassBeach,KSW_Phases.none,3200);
	scr_KSW_AddFish("Bumblebee Tuna","Terraria",spr_KSW_Fish_BumblebeeTuna,spr_KSW_Fish_BumblebeeTuna_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,2900);
	scr_KSW_AddFish("Bunnyfish","Terraria",spr_KSW_Fish_Bunnyfish,spr_KSW_Fish_Bunnyfish_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,1000);
	scr_KSW_AddFish("Cap'n Tunabeard","Terraria",spr_KSW_Fish_CapnTunabeard,spr_KSW_Fish_CapnTunabeard_Pal_Normal,candy,3,grassBeach,KSW_Phases.none,2800);
	scr_KSW_AddFish("Catfish","Terraria",spr_KSW_Fish_Catfish,spr_KSW_Fish_Catfish_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,3200);
	scr_KSW_AddFish("Cloudfish","Terraria",spr_KSW_Fish_Cloudfish,spr_KSW_Fish_Cloudfish_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,1400);
	scr_KSW_AddFish("Clownfish","Terraria",spr_KSW_Fish_Clownfish,spr_KSW_Fish_Clownfish_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,1500);
	scr_KSW_AddFish("Cursedfish","Terraria",spr_KSW_Fish_Cursedfish,spr_KSW_Fish_Cursedfish_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,1700);
	scr_KSW_AddFish("Demonic Hellfish","Terraria",spr_KSW_Fish_DemonicHellfish,spr_KSW_Fish_DemonicHellfish_Pal_Normal,candy,3,hallowReen,KSW_Phases.none,1900);
	scr_KSW_AddFish("Derpfish","Terraria",spr_KSW_Fish_Derpfish,spr_KSW_Fish_Derpfish_Pal_Normal,legion,3,grassBeach,KSW_Phases.none,1600);
	scr_KSW_AddFish("Dirtfish","Terraria",spr_KSW_Fish_Dirtfish,spr_KSW_Fish_Dirtfish_Pal_Normal,mage,3,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Dynamite Fish","Terraria",spr_KSW_Fish_DynamiteFish,spr_KSW_Fish_DynamiteFish_Pal_Normal,candy,3,grassBeach,KSW_Phases.none,3000);
	scr_KSW_AddFish("Eater of Plankton","Terraria",spr_KSW_Fish_EaterOfPlankton,spr_KSW_Fish_EaterOfPlankton_Pal_Normal,mage,3,hallowReen,KSW_Phases.none,4000);
	scr_KSW_AddFish("Fallen Starfish","Terraria",spr_KSW_Fish_FallenStarfish,spr_KSW_Fish_FallenStarfish_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,4400);
	scr_KSW_AddFish("Fishotron","Terraria",spr_KSW_Fish_Fishotron,spr_KSW_Fish_Fishotron_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,5000);
	scr_KSW_AddFish("Fishron","Terraria",spr_KSW_Fish_Fishron,spr_KSW_Fish_Fishron_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Guide Voodoo Fish","Terraria",spr_KSW_Fish_GuideVoodooFish,spr_KSW_Fish_GuideVoodooFish_Pal_Normal,borange,3,hallowReen,KSW_Phases.none,2400);
	scr_KSW_AddFish("Harpyfish","Terraria",spr_KSW_Fish_Harpyfish,spr_KSW_Fish_Harpyfish_Pal_Normal,legion,3,grassBeach,KSW_Phases.none,5200);
	scr_KSW_AddFish("Hungerfish","Terraria",spr_KSW_Fish_Hungerfish,spr_KSW_Fish_Hungerfish_Pal_Normal,candy,3,grassBeach,KSW_Phases.none,5700);
	scr_KSW_AddFish("Ichorfish","Terraria",spr_KSW_Fish_Ichorfish,spr_KSW_Fish_Ichorfish_Pal_Normal,borange,3,hallowReen,KSW_Phases.none,4800);
	scr_KSW_AddFish("Scabbardfish","Terraria",spr_KSW_Fish_InfectedScabbardfish,spr_KSW_Fish_InfectedScabbardfish_Pal_Normal,flux,3,grassBeach,KSW_Phases.none,6300);
	scr_KSW_AddFish("Jewelfish","Terraria",spr_KSW_Fish_Jewelfish,spr_KSW_Fish_Jewelfish_Pal_Normal,mage,3,grassBeach,KSW_Phases.none,5500);
	scr_KSW_AddFish("Mirage Fish","Terraria",spr_KSW_Fish_MirageFish,spr_KSW_Fish_MirageFish_Pal_Normal,flux,3,grassBeach,KSW_Phases.none,5900);
	scr_KSW_AddFish("Mudfish","Terraria",spr_KSW_Fish_Mudfish,spr_KSW_Fish_Mudfish_Pal_Normal,mage,3,grassBeach,KSW_Phases.none,4600);
	scr_KSW_AddFish("Mutant Flinxfin","Terraria",spr_KSW_Fish_MutantFlinxfin,spr_KSW_Fish_MutantFlinxfin_Pal_Normal,glimmer,3,creamCrevasse,KSW_Phases.none,6200);
	scr_KSW_AddFish("Pengfish","Terraria",spr_KSW_Fish_Pengfish,spr_KSW_Fish_Pengfish_Pal_Normal,mage,3,creamCrevasse,KSW_Phases.none,4300);
	scr_KSW_AddFish("Pixiefish","Terraria",spr_KSW_Fish_Pixiefish,spr_KSW_Fish_Pixiefish_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,4400);
	scr_KSW_AddFish("Scarab Fish","Terraria",spr_KSW_Fish_ScarabFish,spr_KSW_Fish_ScarabFish_Pal_Normal,flux,3,grassBeach,KSW_Phases.none,6800);
	scr_KSW_AddFish("Scorpio Fish","Terraria",spr_KSW_Fish_ScorpioFish,spr_KSW_Fish_ScorpioFish_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,6400);
	scr_KSW_AddFish("Slimefish","Terraria",spr_KSW_Fish_Slimefish,spr_KSW_Fish_Slimefish_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,5000);
	scr_KSW_AddFish("Spiderfish","Terraria",spr_KSW_Fish_Spiderfish,spr_KSW_Fish_Spiderfish_Pal_Normal,mage,3,hallowReen,KSW_Phases.none,4700);
	scr_KSW_AddFish("The Fish of Cthulhu","Terraria",spr_KSW_Fish_TheFishOfCthulhu,spr_KSW_Fish_TheFishOfCthulhu_Pal_Normal,candy,3,hallowReen,KSW_Phases.none,7200);
	scr_KSW_AddFish("Tropical Barracuda","Terraria",spr_KSW_Fish_TropicalBarracuda,spr_KSW_Fish_TropicalBarracuda_Pal_Normal,legion,3,grassBeach,KSW_Phases.none,6500);
	scr_KSW_AddFish("Tundra Trout","Terraria",spr_KSW_Fish_TundraTrout,spr_KSW_Fish_TundraTrout_Pal_Normal,mage,3,creamCrevasse,KSW_Phases.none,4200);
	scr_KSW_AddFish("Unicorn Fish","Terraria",spr_KSW_Fish_UnicornFish,spr_KSW_Fish_UnicornFish_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,4600);
	scr_KSW_AddFish("Wyverntail","Terraria",spr_KSW_Fish_Wyverntail,spr_KSW_Fish_Wyverntail_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,7000);
	scr_KSW_AddFish("Zombie Fish","Terraria",spr_KSW_Fish_ZombieFish,spr_KSW_Fish_ZombieFish_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,5600);
	scr_KSW_AddFish("Cheri Berry","Pokemon",spr_KSW_Fish_CheriBerry,spr_KSW_Fish_CheriBerry_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Chesto Berry","Pokemon",spr_KSW_Fish_ChestoBerry,spr_KSW_Fish_ChestoBerry_Pal_Normal,flux,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Pecha Berry","Pokemon",spr_KSW_Fish_PechaBerry,spr_KSW_Fish_PechaBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Rawst Berry","Pokemon",spr_KSW_Fish_RawstBerry,spr_KSW_Fish_RawstBerry_Pal_Normal,mage,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Aspear Berry","Pokemon",spr_KSW_Fish_AspearBerry,spr_KSW_Fish_AspearBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Leppa Berry","Pokemon",spr_KSW_Fish_LeppaBerry,spr_KSW_Fish_LeppaBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Oran Berry","Pokemon",spr_KSW_Fish_OranBerry,spr_KSW_Fish_OranBerry_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Persim Berry","Pokemon",spr_KSW_Fish_PersimBerry,spr_KSW_Fish_PersimBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Lum Berry","Pokemon",spr_KSW_Fish_LumBerry,spr_KSW_Fish_LumBerry_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Sitrus Berry","Pokemon",spr_KSW_Fish_SitrusBerry,spr_KSW_Fish_SitrusBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Figy Berry","Pokemon",spr_KSW_Fish_FigyBerry,spr_KSW_Fish_FigyBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Wiki Berry","Pokemon",spr_KSW_Fish_WikiBerry,spr_KSW_Fish_WikiBerry_Pal_Normal,flux,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Mago Berry","Pokemon",spr_KSW_Fish_MagoBerry,spr_KSW_Fish_MagoBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Aguav Berry","Pokemon",spr_KSW_Fish_AguavBerry,spr_KSW_Fish_AguavBerry_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Iapapa Berry","Pokemon",spr_KSW_Fish_IapapaBerry,spr_KSW_Fish_IapapaBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Razz Berry","Pokemon",spr_KSW_Fish_RazzBerry,spr_KSW_Fish_RazzBerry_Pal_Normal,borange,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Bluk Berry","Pokemon",spr_KSW_Fish_BlukBerry,spr_KSW_Fish_BlukBerry_Pal_Normal,flux,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Nanab Berry","Pokemon",spr_KSW_Fish_NanabBerry,spr_KSW_Fish_NanabBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Wepear Berry","Pokemon",spr_KSW_Fish_WepearBerry,spr_KSW_Fish_WepearBerry_Pal_Normal,mint,0,hallowReen,KSW_Phases.none,50);
	scr_KSW_AddFish("Pinap Berry","Pokemon",spr_KSW_Fish_PinapBerry,spr_KSW_Fish_PinapBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Pomeg Berry","Pokemon",spr_KSW_Fish_PomegBerry,spr_KSW_Fish_PomegBerry_Pal_Normal,borange,0,hallowReen,KSW_Phases.none,40);
	scr_KSW_AddFish("Kelpsy Berry","Pokemon",spr_KSW_Fish_KelpsyBerry,spr_KSW_Fish_KelpsyBerry_Pal_Normal,mage,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Qualot Berry","Pokemon",spr_KSW_Fish_QualotBerry,spr_KSW_Fish_QualotBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Hondew Berry","Pokemon",spr_KSW_Fish_HondewBerry,spr_KSW_Fish_HondewBerry_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Grepa Berry","Pokemon",spr_KSW_Fish_GrepaBerry,spr_KSW_Fish_GrepaBerry_Pal_Normal,borange,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Tamato Berry","Pokemon",spr_KSW_Fish_TamatoBerry,spr_KSW_Fish_TamatoBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Cornn Berry","Pokemon",spr_KSW_Fish_CornnBerry,spr_KSW_Fish_CornnBerry_Pal_Normal,flux,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Magost Berry","Pokemon",spr_KSW_Fish_MagostBerry,spr_KSW_Fish_MagostBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Rabuta Berry","Pokemon",spr_KSW_Fish_RabutaBerry,spr_KSW_Fish_RabutaBerry_Pal_Normal,mint,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Nomel Berry","Pokemon",spr_KSW_Fish_NomelBerry,spr_KSW_Fish_NomelBerry_Pal_Normal,borange,0,hallowReen,KSW_Phases.none,50);
	scr_KSW_AddFish("Spelon Berry","Pokemon",spr_KSW_Fish_SpelonBerry,spr_KSW_Fish_SpelonBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Pamtre Berry","Pokemon",spr_KSW_Fish_PamtreBerry,spr_KSW_Fish_PamtreBerry_Pal_Normal,flux,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Watmel Berry","Pokemon",spr_KSW_Fish_WatmelBerry,spr_KSW_Fish_WatmelBerry_Pal_Normal,mint,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Durin Berry","Pokemon",spr_KSW_Fish_DurinBerry,spr_KSW_Fish_DurinBerry_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Belue Berry","Pokemon",spr_KSW_Fish_BelueBerry,spr_KSW_Fish_BelueBerry_Pal_Normal,flux,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Occa Berry","Pokemon",spr_KSW_Fish_OccaBerry,spr_KSW_Fish_OccaBerry_Pal_Normal,borange,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Passho Berry","Pokemon",spr_KSW_Fish_PasshoBerry,spr_KSW_Fish_PasshoBerry_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Wacan Berry","Pokemon",spr_KSW_Fish_WacanBerry,spr_KSW_Fish_WacanBerry_Pal_Normal,mint,0,hallowReen,KSW_Phases.none,40);
	scr_KSW_AddFish("Rindo Berry","Pokemon",spr_KSW_Fish_RindoBerry,spr_KSW_Fish_RindoBerry_Pal_Normal,mint,0,hallowReen,KSW_Phases.none,40);
	scr_KSW_AddFish("Yache Berry","Pokemon",spr_KSW_Fish_YacheBerry,spr_KSW_Fish_YacheBerry_Pal_Normal,legion,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Chople Berry","Pokemon",spr_KSW_Fish_ChopleBerry,spr_KSW_Fish_ChopleBerry_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Kebia Berry","Pokemon",spr_KSW_Fish_KebiaBerry,spr_KSW_Fish_KebiaBerry_Pal_Normal,mint,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Shuca Berry","Pokemon",spr_KSW_Fish_ShucaBerry,spr_KSW_Fish_ShucaBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Coba Berry","Pokemon",spr_KSW_Fish_CobaBerry,spr_KSW_Fish_CobaBerry_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Payapa Berry","Pokemon",spr_KSW_Fish_PayapaBerry,spr_KSW_Fish_PayapaBerry_Pal_Normal,flux,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Tanga Berry","Pokemon",spr_KSW_Fish_TangaBerry,spr_KSW_Fish_TangaBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Charti Berry","Pokemon",spr_KSW_Fish_ChartiBerry,spr_KSW_Fish_ChartiBerry_Pal_Normal,borange,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Kasib Berry","Pokemon",spr_KSW_Fish_KasibBerry,spr_KSW_Fish_KasibBerry_Pal_Normal,flux,0,hallowReen,KSW_Phases.none,50);
	scr_KSW_AddFish("Haban Berry","Pokemon",spr_KSW_Fish_HabanBerry,spr_KSW_Fish_HabanBerry_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Colbur Berry","Pokemon",spr_KSW_Fish_ColburBerry,spr_KSW_Fish_ColburBerry_Pal_Normal,flux,0,hallowReen,KSW_Phases.none,60);
	scr_KSW_AddFish("Babiri Berry","Pokemon",spr_KSW_Fish_BabiriBerry,spr_KSW_Fish_BabiriBerry_Pal_Normal,mint,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Chilan Berry","Pokemon",spr_KSW_Fish_ChilanBerry,spr_KSW_Fish_ChilanBerry_Pal_Normal,borange,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Liechi Berry","Pokemon",spr_KSW_Fish_LiechiBerry,spr_KSW_Fish_LiechiBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Ganlon Berry","Pokemon",spr_KSW_Fish_GanlonBerry,spr_KSW_Fish_GanlonBerry_Pal_Normal,flux,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Salac Berry","Pokemon",spr_KSW_Fish_SalacBerry,spr_KSW_Fish_SalacBerry_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Petaya Berry","Pokemon",spr_KSW_Fish_PetayaBerry,spr_KSW_Fish_PetayaBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Apicot Berry","Pokemon",spr_KSW_Fish_ApicotBerry,spr_KSW_Fish_ApicotBerry_Pal_Normal,legion,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Lansat Berry","Pokemon",spr_KSW_Fish_LansatBerry,spr_KSW_Fish_LansatBerry_Pal_Normal,glimmer,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Starf Berry","Pokemon",spr_KSW_Fish_StarfBerry,spr_KSW_Fish_StarfBerry_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Enigma Berry","Pokemon",spr_KSW_Fish_EnigmaBerry,spr_KSW_Fish_EnigmaBerry_Pal_Normal,mage,0,hallowReen,KSW_Phases.none,50);
	scr_KSW_AddFish("Micle Berry","Pokemon",spr_KSW_Fish_MicleBerry,spr_KSW_Fish_MicleBerry_Pal_Normal,mint,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Custap Berry","Pokemon",spr_KSW_Fish_CustapBerry,spr_KSW_Fish_CustapBerry_Pal_Normal,candy,0,hallowReen,KSW_Phases.none,60);
	scr_KSW_AddFish("Jaboca Berry","Pokemon",spr_KSW_Fish_JabocaBerry,spr_KSW_Fish_JabocaBerry_Pal_Normal,borange,0,hallowReen,KSW_Phases.none,60);
	scr_KSW_AddFish("Rowap Berry","Pokemon",spr_KSW_Fish_RowapBerry,spr_KSW_Fish_RowapBerry_Pal_Normal,legion,0,hallowReen,KSW_Phases.none,40);
	scr_KSW_AddFish("Roseli Berry","Pokemon",spr_KSW_Fish_RoseliBerry,spr_KSW_Fish_RoseliBerry_Pal_Normal,candy,0,hallowReen,KSW_Phases.none,60);
	scr_KSW_AddFish("Kee Berry","Pokemon",spr_KSW_Fish_KeeBerry,spr_KSW_Fish_KeeBerry_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Maranga Berry","Pokemon",spr_KSW_Fish_MarangaBerry,spr_KSW_Fish_MarangaBerry_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Chainsaw Fish","Wario",spr_KSW_Fish_ChainsawFish,spr_KSW_Fish_ChainsawFish_Pal_Normal,mage,1,grassBeach,KSW_Phases.night,6000,-16,0);
	scr_KSW_AddFish("7 Colored Fish","Yu-Gi-Oh!",spr_KSW_Fish_7ColoredFish,spr_KSW_Fish_7ColoredFish_Pal_Normal,mint,2,grassBeach,KSW_Phases.night,9000,-10,-12);
	scr_KSW_AddFish("Magikarp","Pokemon",spr_KSW_Fish_Magikarp,spr_KSW_Fish_Magikarp_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,500,-4,0);
	scr_KSW_AddFish("Gyrados","Pokemon",spr_KSW_Fish_Gyrados,spr_KSW_Fish_Gyrados_Pal_Normal,legion,2,grassBeach,KSW_Phases.day,20000,-22,4);
	scr_KSW_AddFish("Goldeen","Pokemon",spr_KSW_Fish_Goldeen,spr_KSW_Fish_Goldeen_Pal_Normal,borange,0,grassBeach,KSW_Phases.day,400,-1,0);
	scr_KSW_AddFish("Seaking","Pokemon",spr_KSW_Fish_Seaking,spr_KSW_Fish_Seaking_Pal_Normal,borange,1,grassBeach,KSW_Phases.day,4000,-2,0);
	scr_KSW_AddFish("Horsea","Pokemon",spr_KSW_Fish_Horsea,spr_KSW_Fish_Horsea_Pal_Normal,mage,0,grassBeach,KSW_Phases.afternoon,350,1,0);
	scr_KSW_AddFish("Seadra","Pokemon",spr_KSW_Fish_Seadra,spr_KSW_Fish_Seadra_Pal_Normal,mage,1,grassBeach,KSW_Phases.afternoon,2500,2,-1);
	scr_KSW_AddFish("Kingdra","Pokemon",spr_KSW_Fish_Kingdra,spr_KSW_Fish_Kingdra_Pal_Normal,mage,2,grassBeach,KSW_Phases.afternoon,12000,-2,2);
	scr_KSW_AddFish("Krabby","Pokemon",spr_KSW_Fish_Krabby,spr_KSW_Fish_Krabby_Pal_Normal,candy,0,grassBeach,KSW_Phases.day,1000,0,-2);
	scr_KSW_AddFish("Kingler","Pokemon",spr_KSW_Fish_Kingler,spr_KSW_Fish_Kingler_Pal_Normal,candy,1,grassBeach,KSW_Phases.day,7000,0,-4);
	scr_KSW_AddFish("Omanyte","Pokemon",spr_KSW_Fish_Omanyte,spr_KSW_Fish_Omanyte_Pal_Normal,legion,1,grassBeach,KSW_Phases.afternoon,4000);
	scr_KSW_AddFish("Omastar","Pokemon",spr_KSW_Fish_Omastar,spr_KSW_Fish_Omastar_Pal_Normal,legion,2,grassBeach,KSW_Phases.afternoon,9000,0,-2);
	scr_KSW_AddFish("Lapras","Pokemon",spr_KSW_Fish_Lapras,spr_KSW_Fish_Lapras_Pal_Normal,mage,2,creamCrevasse,KSW_Phases.none,30000,-6,6);
	scr_KSW_AddFish("Kabuto","Pokemon",spr_KSW_Fish_Kabuto,spr_KSW_Fish_Kabuto_Pal_Normal,borange,1,grassBeach,KSW_Phases.night,3000);
	scr_KSW_AddFish("Kabutops","Pokemon",spr_KSW_Fish_Kabutops,spr_KSW_Fish_Kabutops_Pal_Normal,borange,2,grassBeach,KSW_Phases.night,8000,0,-2);
	scr_KSW_AddFish("Tentacool","Pokemon",spr_KSW_Fish_Tentacool,spr_KSW_Fish_Tentacool_Pal_Normal,mage,0,grassBeach,KSW_Phases.night,1000,-1,0);
	scr_KSW_AddFish("Tentacruel","Pokemon",spr_KSW_Fish_Tentacruel,spr_KSW_Fish_Tentacruel_Pal_Normal,mage,1,grassBeach,KSW_Phases.night,4200);
	scr_KSW_AddFish("Staryu","Pokemon",spr_KSW_Fish_Staryu,spr_KSW_Fish_Staryu_Pal_Normal,borange,0,grassBeach,KSW_Phases.afternoon,750);
	scr_KSW_AddFish("Starmie","Pokemon",spr_KSW_Fish_Starmie,spr_KSW_Fish_Starmie_Pal_Normal,flux,1,grassBeach,KSW_Phases.afternoon,3200);
	scr_KSW_AddFish("Slowpoke","Pokemon",spr_KSW_Fish_Slowpoke,spr_KSW_Fish_Slowpoke_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.day,800);
	scr_KSW_AddFish("Slowbro","Pokemon",spr_KSW_Fish_Slowbro,spr_KSW_Fish_Slowbro_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.day,3600,-2,-2);
	scr_KSW_AddFish("Slowking","Pokemon",spr_KSW_Fish_Slowking,spr_KSW_Fish_Slowking_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.day,9800,0,-3);
	scr_KSW_AddFish("Shellder","Pokemon",spr_KSW_Fish_Shellder,spr_KSW_Fish_Shellder_Pal_Normal,flux,0,grassBeach,KSW_Phases.day,600,-1,0);
	scr_KSW_AddFish("Cloyster","Pokemon",spr_KSW_Fish_Cloyster,spr_KSW_Fish_Cloyster_Pal_Normal,flux,1,grassBeach,KSW_Phases.day,2700,-2,-2);
	scr_KSW_AddFish("Squirtle","Pokemon",spr_KSW_Fish_Squirtle,spr_KSW_Fish_Squirtle_Pal_Normal,legion,1,grassBeach,KSW_Phases.day,1200);
	scr_KSW_AddFish("Wartortle","Pokemon",spr_KSW_Fish_Wartortle,spr_KSW_Fish_Wartortle_Pal_Normal,legion,2,grassBeach,KSW_Phases.day,9000);
	scr_KSW_AddFish("Blastoise","Pokemon",spr_KSW_Fish_Blastoise,spr_KSW_Fish_Blastoise_Pal_Normal,legion,3,grassBeach,KSW_Phases.day,20000);
	scr_KSW_AddFish("Seel","Pokemon",spr_KSW_Fish_Seel,spr_KSW_Fish_Seel_Pal_Normal,glimmer,0,creamCrevasse,KSW_Phases.none,900);
	scr_KSW_AddFish("Dewgong","Pokemon",spr_KSW_Fish_Dewgong,spr_KSW_Fish_Dewgong_Pal_Normal,glimmer,1,creamCrevasse,KSW_Phases.none,2600,-5,-1);
	scr_KSW_AddFish("Psyduck","Pokemon",spr_KSW_Fish_Psyduck,spr_KSW_Fish_Psyduck_Pal_Normal,borange,0,grassBeach,KSW_Phases.day,750,0,-2);
	scr_KSW_AddFish("Golduck","Pokemon",spr_KSW_Fish_Golduck,spr_KSW_Fish_Golduck_Pal_Normal,mage,1,grassBeach,KSW_Phases.day,3000,2,4);
	scr_KSW_AddFish("Poliwag","Pokemon",spr_KSW_Fish_Poliwag,spr_KSW_Fish_Poliwag_Pal_Normal,legion,0,grassBeach,KSW_Phases.afternoon,500,-2,0);
	scr_KSW_AddFish("Poliwhirl","Pokemon",spr_KSW_Fish_Poliwhirl,spr_KSW_Fish_Poliwhirl_Pal_Normal,legion,1,grassBeach,KSW_Phases.day,2200);
	scr_KSW_AddFish("Poliwrath","Pokemon",spr_KSW_Fish_Poliwrath,spr_KSW_Fish_Poliwrath_Pal_Normal,legion,2,grassBeach,KSW_Phases.day,8000,0,-4);
	scr_KSW_AddFish("Politoed","Pokemon",spr_KSW_Fish_Politoed,spr_KSW_Fish_Politoed_Pal_Normal,mint,2,grassBeach,KSW_Phases.day,7200,0,-2);
	scr_KSW_AddFish("Dratini","Pokemon",spr_KSW_Fish_Dratini,spr_KSW_Fish_Dratini_Pal_Normal,mage,1,grassBeach,KSW_Phases.afternoon,1000,-2,-1);
	scr_KSW_AddFish("Dragonair","Pokemon",spr_KSW_Fish_Dragonair,spr_KSW_Fish_Dragonair_Pal_Normal,mage,2,grassBeach,KSW_Phases.afternoon,6900,-5,0);
	scr_KSW_AddFish("Dragonite","Pokemon",spr_KSW_Fish_Dragonite,spr_KSW_Fish_Dragonite_Pal_Normal,borange,3,grassBeach,KSW_Phases.afternoon,22000,0,4);
	scr_KSW_AddFish("Godzilla","Godzilla",spr_KSW_Fish_Godzilla,spr_KSW_Fish_Godzilla_Pal_Normal,mint,3,grassBeach,KSW_Phases.day,100000,-10,14);
	scr_KSW_AddFish("Rahab","Castlevania",spr_KSW_Fish_Rahab,spr_KSW_Fish_Rahab_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.night,8000);
	scr_KSW_AddFish("Plesioth","Monster Hunter",spr_KSW_Fish_Plesioth,spr_KSW_Fish_Plesioth_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.afternoon,80000,-16,18);
	scr_KSW_AddFish("Cacodemon","DOOM",spr_KSW_Fish_Cacodemon,spr_KSW_Fish_Cacodemon_Pal_Normal,mint,3,grassBeach,KSW_Phases.night,6600,-6,4);
	scr_KSW_AddFish("Wolpole","Pikmin",spr_KSW_Fish_Wolpole,spr_KSW_Fish_Wolpole_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.night,400,4,1);
	scr_KSW_AddFish("Water Dumple","Pikmin",spr_KSW_Fish_WaterDumple,spr_KSW_Fish_WaterDumple_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.night,1200,-6,-1);
	scr_KSW_AddFish("Yellow Wollyhop","Pikmin",spr_KSW_Fish_YellowWollyhop,spr_KSW_Fish_YellowWollyhop_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.afternoon,2700,-2,3);
	scr_KSW_AddFish("Toady Bloyster","Pikmin",spr_KSW_Fish_ToadyBloyster,spr_KSW_Fish_ToadyBloyster_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.day,6600,-17,0);
	scr_KSW_AddFish("Puckering Blinnow","Pikmin",spr_KSW_Fish_PuckeringBlinnow,spr_KSW_Fish_PuckeringBlinnow_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.day,5400,-11,-1);
	scr_KSW_AddFish("Fish Taco","Soft & Wet",spr_KSW_Fish_FishTaco,spr_KSW_Fish_FishTaco_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,2500,0,0,-1,snd_KSW_Fish_FishTaco);
	scr_KSW_AddFish("Swedish Fish","",spr_KSW_Fish_SwedishFish,spr_KSW_Fish_SwedishFish_Pal_Normal,mint,3,grassBeach,KSW_Phases.day,10,-30,0);
	scr_KSW_AddFish("Archfiend Skull","Deirdre",spr_KSW_Fish_ArchfiendSkull,spr_KSW_Fish_ArchfiendSkull_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,5000);
	scr_KSW_AddFish("Ghost Hamster","Deirdre",spr_KSW_Fish_GhostHamster,spr_KSW_Fish_GhostHamster_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,7800);
	scr_KSW_AddFish("Mizzle","Deltarune",spr_KSW_Fish_Mizzle,spr_KSW_Fish_Mizzle_Pal_Normal,mage,1,grassBeach,KSW_Phases.night,2000,-8,8);
	scr_KSW_AddFish("Pluey","Deltarune",spr_KSW_Fish_Pluey,spr_KSW_Fish_Pluey_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,4800,0,0,-1,snd_KSW_Fish_Pluey);
	scr_KSW_AddFish("Annoying Dogfish","Undertale",spr_KSW_Fish_AnnoyingDogfish,spr_KSW_Fish_AnnoyingDogfish_Pal_Normal,mint,3,grassBeach,KSW_Phases.day,20015);
	scr_KSW_AddFish("SPAMFISH","Deltarune",spr_KSW_Fish_Spamfish,spr_KSW_Fish_Spamfish_Pal_Normal,glimmer,3,grassBeach,KSW_Phases.none,1997,-26,-12);
	var tenna = scr_KSW_AddFish("Mr Ant Tenna","Deltarune",spr_KSW_Fish_MrAntTenna,spr_KSW_Fish_MrAntTenna_Pal_Normal,tvtime,3,grassBeach,KSW_Phases.none,300000,0,20,-1,snd_KSW_Fish_Tenna);
	tenna.phaseIconRight = spr_KSW_Menu_TitleScreen_Phase_TVTime;
	scr_KSW_AddFish("Aquatic Spawn","Deltarune",spr_KSW_Fish_AquaticSpawn,spr_KSW_Fish_AquaticSpawn_Pal_Normal,flux,3,creamCrevasse,KSW_Phases.none,122597,12,12,-1,snd_KSW_Fish_TitanSpawn);
	scr_KSW_AddFish("Quirky Knight","Deirdre",spr_KSW_Fish_QuirkyKnight,spr_KSW_Fish_QuirkyKnight_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,20000,0,8);
	scr_KSW_AddFish("Big Lenny","SpongeBob",spr_KSW_Fish_Big_Lenny_Normal,spr_KSW_Fish_Big_Lenny_Pal_Normal,flux,3,grassBeach,KSW_Phases.night,100000,23,10);
	scr_KSW_AddFish("Game Shark","Soft & Wet",spr_KSW_Fish_GameShark,spr_KSW_Fish_GameShark_Pal_Normal,legion,3,grassBeach,KSW_Phases.afternoon,8000,-12,4);
	scr_KSW_AddFish("Gulugulugulu Wator Fish","",spr_KSW_Fish_GuluguluguluFish,spr_KSW_Fish_GuluguluguluFish_Pal_Normal,mint,3,grassBeach,KSW_Phases.afternoon,100000);
	scr_KSW_AddFish("Egg Fish","Cave Story",spr_KSW_Fish_EggFish,spr_KSW_Fish_EggFish_Pal_Normal,borange,1,grassBeach,KSW_Phases.afternoon,2000,-4,0);
	scr_KSW_AddFish("Ikachan","Cave Story",spr_KSW_Fish_Ikachan,spr_KSW_Fish_Ikachan_Pal_Normal,mage,2,grassBeach,KSW_Phases.night,4600);
	scr_KSW_AddFish("Ironhead","Cave Story",spr_KSW_Fish_Ironhead,spr_KSW_Fish_Ironhead_Pal_Normal,legion,3,grassBeach,KSW_Phases.night,55480,-46,-10);
	scr_KSW_AddFish("Sea-Shroom","Plants vs. Zombies",spr_KSW_Fish_SeaShroom,spr_KSW_Fish_SeaShroom_Pal_Normal,mint,2,grassBeach,KSW_Phases.night,5000);
	scr_KSW_AddFish("Tangle Kelp","Plants vs. Zombies",spr_KSW_Fish_TangleKelp,spr_KSW_Fish_TangleKelp_Pal_Normal,mint,2,grassBeach,KSW_Phases.day,5000);
	scr_KSW_AddFish("Snorkel Zombie","Plants vs. Zombies",spr_KSW_Fish_SnorkelZombie,spr_KSW_Fish_SnorkelZombie_Pal_Normal,mint,3,hallowReen,KSW_Phases.none,12000,-16,6);
	scr_KSW_AddFish("Rotten Flesh","Minecraft",spr_KSW_Fish_RottenFlesh,spr_KSW_Fish_RottenFlesh_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Leather Boots","Minecraft",spr_KSW_Fish_LeatherBoots,spr_KSW_Fish_LeatherBoots_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Leather","Minecraft",spr_KSW_Fish_Leather,spr_KSW_Fish_Leather_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Bowl","Minecraft",spr_KSW_Fish_Bowl,spr_KSW_Fish_Bowl_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Stick","Minecraft",spr_KSW_Fish_Stick,spr_KSW_Fish_Stick_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Bone","Minecraft",spr_KSW_Fish_Bone,spr_KSW_Fish_Bone_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("String","Minecraft",spr_KSW_Fish_String,spr_KSW_Fish_String_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Baggie","Soft & Wet",spr_KSW_Fish_Baggie,spr_KSW_Fish_Baggie_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,20000,0,3);
	scr_KSW_AddFish("Omni Fish","Soft & Wet",spr_KSW_Fish_OmniFish,spr_KSW_Fish_OmniFish_Pal_Normal,legion,3,grassBeach,KSW_Phases.night,500000);
	scr_KSW_AddFish("Invader Squid","Space Invaders",spr_KSW_Fish_InvaderSquid,spr_KSW_Fish_InvaderSquid_Pal_Normal,mint,1,grassBeach,KSW_Phases.night,3000);
	scr_KSW_AddFish("Invader Crab","Space Invaders",spr_KSW_Fish_InvaderCrab,spr_KSW_Fish_InvaderCrab_Pal_Normal,mage,1,grassBeach,KSW_Phases.night,2000);
	scr_KSW_AddFish("Invader Octopus","Space Invaders",spr_KSW_Fish_InvaderOctopus,spr_KSW_Fish_InvaderOctopus_Pal_Normal,borange,1,grassBeach,KSW_Phases.night,1000);
	scr_KSW_AddFish("Invader UFO","Space Invaders",spr_KSW_Fish_InvaderUFO,spr_KSW_Fish_InvaderUFO_Pal_Normal,flux,3,grassBeach,KSW_Phases.night,12800);
	scr_KSW_AddFish("Kalamar","The Binding\nof Isaac",spr_KSW_Fish_Kalamar,spr_KSW_Fish_Kalamar_Pal_Normal,legion,2,grassBeach,KSW_Phases.night,4000);
	scr_KSW_AddFish("Pipe Fiend","The Binding\nof Isaac",spr_KSW_Fish_PipeFiend,spr_KSW_Fish_PipeFiend_Pal_Normal,legion,2,grassBeach,KSW_Phases.night,5000);
	scr_KSW_AddFish("Prey","The Binding\nof Isaac",spr_KSW_Fish_Prey,spr_KSW_Fish_Prey_Pal_Normal,legion,2,grassBeach,KSW_Phases.night,4500,,,,snd_KSW_Fish_Prey);
	scr_KSW_AddFish("Lil' Blub","The Binding\nof Isaac",spr_KSW_Fish_LilBlub,spr_KSW_Fish_LilBlub_Pal_Normal,mint,3,grassBeach,KSW_Phases.night,15000,0,10,,snd_KSW_Fish_LilBlub);
	scr_KSW_AddFish("Strawberry","Kirby",spr_KSW_Fish_Strawberry,spr_KSW_Fish_Strawberry_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Tomato","Kirby",spr_KSW_Fish_Tomato,spr_KSW_Fish_Tomato_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Cherries","Kirby",spr_KSW_Fish_Cherries,spr_KSW_Fish_Cherries_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Watermelon","Kirby",spr_KSW_Fish_Watermelon,spr_KSW_Fish_Watermelon_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Melon","Kirby",spr_KSW_Fish_Melon,spr_KSW_Fish_Melon_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Orange","Kirby",spr_KSW_Fish_Orange,spr_KSW_Fish_Orange_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Bananas","Kirby",spr_KSW_Fish_Bananas,spr_KSW_Fish_Bananas_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Peach","Kirby",spr_KSW_Fish_Peach,spr_KSW_Fish_Peach_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Carrot","Kirby",spr_KSW_Fish_Carrot,spr_KSW_Fish_Carrot_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Green Pepper","Kirby",spr_KSW_Fish_GreenPepper,spr_KSW_Fish_GreenPepper_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Kabocha","Kirby",spr_KSW_Fish_Kabocha,spr_KSW_Fish_Kabocha_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Peas","Kirby",spr_KSW_Fish_Peas,spr_KSW_Fish_Peas_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Corn","Kirby",spr_KSW_Fish_Corn,spr_KSW_Fish_Corn_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Milk Carton","Kirby",spr_KSW_Fish_MilkCarton,spr_KSW_Fish_MilkCarton_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Milk Bottle","Kirby",spr_KSW_Fish_MilkBottle,spr_KSW_Fish_MilkBottle_Pal_Normal,mage,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Bread","Kirby",spr_KSW_Fish_Bread,spr_KSW_Fish_Bread_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Donut","Kirby",spr_KSW_Fish_Donut,spr_KSW_Fish_Donut_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Pancakes","Kirby",spr_KSW_Fish_Pancakes,spr_KSW_Fish_Pancakes_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Sandwich","Kirby",spr_KSW_Fish_Sandwich,spr_KSW_Fish_Sandwich_Pal_Normal,mint,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Hot Dog","Kirby",spr_KSW_Fish_HotDog,spr_KSW_Fish_HotDog_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Burger","Kirby",spr_KSW_Fish_Burger,spr_KSW_Fish_Burger_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Roast Chicken","Kirby",spr_KSW_Fish_RoastChicken,spr_KSW_Fish_RoastChicken_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Lobster Dish","Kirby",spr_KSW_Fish_LobsterDish,spr_KSW_Fish_LobsterDish_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,60);
	scr_KSW_AddFish("Fried Eggs","Kirby",spr_KSW_Fish_FriedEggs,spr_KSW_Fish_FriedEggs_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("French Fries","Kirby",spr_KSW_Fish_FrenchFries,spr_KSW_Fish_FrenchFries_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Cupcake","Kirby",spr_KSW_Fish_Cupcake,spr_KSW_Fish_Cupcake_Pal_Normal,glimmer,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Cookie","Kirby",spr_KSW_Fish_Cookie,spr_KSW_Fish_Cookie_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Shaved Ice","Kirby",spr_KSW_Fish_ShavedIce,spr_KSW_Fish_ShavedIce_Pal_Normal,mage,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Ice Cream Cone","Kirby",spr_KSW_Fish_IceCreamCone,spr_KSW_Fish_IceCreamCone_Pal_Normal,mage,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Ice Cream Bar","Kirby",spr_KSW_Fish_IceCreamBar,spr_KSW_Fish_IceCreamBar_Pal_Normal,legion,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Flan","Kirby",spr_KSW_Fish_Flan,spr_KSW_Fish_Flan_Pal_Normal,borange,0,creamCrevasse,KSW_Phases.none,60);
	scr_KSW_AddFish("Cream Soda","Kirby",spr_KSW_Fish_CreamSoda,spr_KSW_Fish_CreamSoda_Pal_Normal,mint,0,creamCrevasse,KSW_Phases.none,50);
	scr_KSW_AddFish("Orange Juice","Kirby",spr_KSW_Fish_OrangeJuice,spr_KSW_Fish_OrangeJuice_Pal_Normal,borange,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Coffee","Kirby",spr_KSW_Fish_Coffee,spr_KSW_Fish_Coffee_Pal_Normal,legion,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Soda Can","Kirby",spr_KSW_Fish_SodaCan,spr_KSW_Fish_SodaCan_Pal_Normal,candy,0,grassBeach,KSW_Phases.none,40);
	scr_KSW_AddFish("Candy Cane","Kirby",spr_KSW_Fish_CandyCane,spr_KSW_Fish_CandyCane_Pal_Normal,candy,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Candy","Kirby",spr_KSW_Fish_Candy,spr_KSW_Fish_Candy_Pal_Normal,candy,0,creamCrevasse,KSW_Phases.none,40);
	scr_KSW_AddFish("Crepe","Kirby",spr_KSW_Fish_Crepe,spr_KSW_Fish_Crepe_Pal_Normal,glimmer,0,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Maxim Tomato","Kirby",spr_KSW_Fish_MaximTomato,spr_KSW_Fish_MaximTomato_Pal_Normal,candy,1,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Invincibility Candy","Kirby",spr_KSW_Fish_InvincibilityCandy,spr_KSW_Fish_InvincibilityCandy_Pal_Normal,glimmer,1,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Extra Life","Kirby",spr_KSW_Fish_ExtraLife,spr_KSW_Fish_ExtraLife_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,2500);
	scr_KSW_AddFish("Treasure Chest","Kirby",spr_KSW_Fish_TreasureChest,spr_KSW_Fish_TreasureChest_Pal_Normal,candy,3,grassBeach,KSW_Phases.none,15000,-2);
	scr_KSW_AddFish("Star Coin","Kirby",spr_KSW_Fish_StarCoin,spr_KSW_Fish_StarCoin_Pal_Normal,borange,3,grassBeach,KSW_Phases.none,10000);
	scr_KSW_AddFish("Gold Medal","Kirby",spr_KSW_Fish_GoldMedal,spr_KSW_Fish_GoldMedal_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,1000);
	scr_KSW_AddFish("Gold Coin","Kirby",spr_KSW_Fish_GoldCoin,spr_KSW_Fish_GoldCoin_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,100);
	scr_KSW_AddFish("Whip","Kirby",spr_KSW_Fish_Whip,spr_KSW_Fish_Whip_Pal_Normal,borange,2,hallowReen,KSW_Phases.none,6800);
	scr_KSW_AddFish("Crystal Ball","Kirby",spr_KSW_Fish_CrystalBall,spr_KSW_Fish_CrystalBall_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Lucky Cat","Kirby",spr_KSW_Fish_LuckyCat,spr_KSW_Fish_LuckyCat_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,500);
	scr_KSW_AddFish("Seiryu Sword","Kirby",spr_KSW_Fish_SeiryuSword,spr_KSW_Fish_SeiryuSword_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,1420);
	scr_KSW_AddFish("Screw Attack","Kirby",spr_KSW_Fish_ScrewAttack,spr_KSW_Fish_ScrewAttack_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,8000);
	scr_KSW_AddFish("Echigo Candy","Kirby",spr_KSW_Fish_EchigoCandy,spr_KSW_Fish_EchigoCandy_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,8000);
	scr_KSW_AddFish("Phanto Mask","Mario",spr_KSW_Fish_PhantoMask,spr_KSW_Fish_PhantoMask_Pal_Normal,legion,2,hallowReen,KSW_Phases.none,2780);
	scr_KSW_AddFish("Star Stone","Kirby",spr_KSW_Fish_StarStone,spr_KSW_Fish_StarStone_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,8210);
	scr_KSW_AddFish("Beast Fang","Kirby",spr_KSW_Fish_BeastFang,spr_KSW_Fish_BeastFang_Pal_Normal,borange,2,hallowReen,KSW_Phases.none,7300);
	scr_KSW_AddFish("Bandanna","Kirby",spr_KSW_Fish_Bandanna,spr_KSW_Fish_Bandanna_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,1990);
	scr_KSW_AddFish("Springtime","Kirby",spr_KSW_Fish_Springtime,spr_KSW_Fish_Springtime_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,2500);
	scr_KSW_AddFish("Seasons Heart","Kirby",spr_KSW_Fish_SeasonsHeart,spr_KSW_Fish_SeasonsHeart_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,2500);
	scr_KSW_AddFish("Dime","Kirby",spr_KSW_Fish_Dime,spr_KSW_Fish_Dime_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,10);
	scr_KSW_AddFish("Glass Slipper","Kirby",spr_KSW_Fish_GlassSlipper,spr_KSW_Fish_GlassSlipper_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,1200);
	scr_KSW_AddFish("Goblet","Kirby",spr_KSW_Fish_Goblet,spr_KSW_Fish_Goblet_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,800);
	scr_KSW_AddFish("Sauce Pan","Kirby",spr_KSW_Fish_SaucePan,spr_KSW_Fish_SaucePan_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,10);
	scr_KSW_AddFish("Brass Knuckle","Kirby",spr_KSW_Fish_BrassKnuckle,spr_KSW_Fish_BrassKnuckle_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Amber Rose","Kirby",spr_KSW_Fish_AmberRose,spr_KSW_Fish_AmberRose_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,2210);
	scr_KSW_AddFish("Fish Fossil","Kirby",spr_KSW_Fish_FishFossil,spr_KSW_Fish_FishFossil_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,8250);
	scr_KSW_AddFish("Beast Fossil","Kirby",spr_KSW_Fish_BeastFossil,spr_KSW_Fish_BeastFossil_Pal_Normal,legion,2,hallowReen,KSW_Phases.none,2422);
	scr_KSW_AddFish("Nunchucks","Kirby",spr_KSW_Fish_Nunchucks,spr_KSW_Fish_Nunchucks_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,5548);
	scr_KSW_AddFish("Machine Parts","Kirby",spr_KSW_Fish_MachineParts,spr_KSW_Fish_MachineParts_Pal_Normal,mint,2,grassBeach,KSW_Phases.none,1213);
	scr_KSW_AddFish("Bucket","Mario",spr_KSW_Fish_Bucket,spr_KSW_Fish_Bucket_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,200);
	scr_KSW_AddFish("Summertime","Kirby",spr_KSW_Fish_Summertime,spr_KSW_Fish_Summertime_Pal_Normal,mint,2,grassBeach,KSW_Phases.none,2500);
	scr_KSW_AddFish("Power Paintbrush","Kirby",spr_KSW_Fish_PowerPaintbrush,spr_KSW_Fish_PowerPaintbrush_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,2220);
	scr_KSW_AddFish("100-Dollar Coin","Kirby",spr_KSW_Fish_100DollarCoin,spr_KSW_Fish_100DollarCoin_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,1000);
	scr_KSW_AddFish("Ancient Gem","Kirby",spr_KSW_Fish_AncientGem,spr_KSW_Fish_AncientGem_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,6800);
	scr_KSW_AddFish("Falcon Helmet","F-Zero",spr_KSW_Fish_FalconHelmet,spr_KSW_Fish_FalconHelmet_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,4100);
	scr_KSW_AddFish("Dud","Kirby",spr_KSW_Fish_Dud,spr_KSW_Fish_Dud_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,30);
	scr_KSW_AddFish("Cell Phone","Kirby",spr_KSW_Fish_CellPhone,spr_KSW_Fish_CellPhone_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,4021);
	scr_KSW_AddFish("Truth Mirror","Kirby",spr_KSW_Fish_TruthMirror,spr_KSW_Fish_TruthMirror_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,5000);
	scr_KSW_AddFish("Star Tiara","Kirby",spr_KSW_Fish_StarTiara,spr_KSW_Fish_StarTiara_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,4082);
	scr_KSW_AddFish("Koopa Shell","Mario",spr_KSW_Fish_KoopaShell,spr_KSW_Fish_KoopaShell_Pal_Normal,mint,2,grassBeach,KSW_Phases.none,800);
	scr_KSW_AddFish("Falchion","Fire Emblem",spr_KSW_Fish_Falchion,spr_KSW_Fish_Falchion_Pal_Normal,mint,2,grassBeach,KSW_Phases.none,3250);
	scr_KSW_AddFish("Warrior Shield","Kirby",spr_KSW_Fish_WarriorShield,spr_KSW_Fish_WarriorShield_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,5000);
	scr_KSW_AddFish("Unicorn Horn","Kirby",spr_KSW_Fish_UnicornHorn,spr_KSW_Fish_UnicornHorn_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,8030);
	scr_KSW_AddFish("Autumntime","Kirby",spr_KSW_Fish_Autumntime,spr_KSW_Fish_Autumntime_Pal_Normal,borange,2,hallowReen,KSW_Phases.none,2500);
	scr_KSW_AddFish("Three-Star Cane","Kirby",spr_KSW_Fish_ThreeStarCane,spr_KSW_Fish_ThreeStarCane_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,2220);
	scr_KSW_AddFish("Broken Bowl","Kirby",spr_KSW_Fish_BrokenBowl,spr_KSW_Fish_BrokenBowl_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,50);
	scr_KSW_AddFish("Tut Mask","Kirby",spr_KSW_Fish_TutMask,spr_KSW_Fish_TutMask_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,1600);
	scr_KSW_AddFish("Mr Saturn","Mother",spr_KSW_Fish_MrSaturn,spr_KSW_Fish_MrSaturn_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,1200);
	scr_KSW_AddFish("Armor","Kirby",spr_KSW_Fish_Armor,spr_KSW_Fish_Armor_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,2120);
	scr_KSW_AddFish("Treasure Box","Kirby",spr_KSW_Fish_TreasureBox,spr_KSW_Fish_TreasureBox_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,1000);
	scr_KSW_AddFish("Mannequin","Kirby",spr_KSW_Fish_Mannequin,spr_KSW_Fish_Mannequin_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,3000);
	scr_KSW_AddFish("Gold Crown","Kirby",spr_KSW_Fish_GoldCrown,spr_KSW_Fish_GoldCrown_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,5280);
	scr_KSW_AddFish("King Cape","Kirby",spr_KSW_Fish_KingCape,spr_KSW_Fish_KingCape_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,5080);
	scr_KSW_AddFish("Model Ship","Kirby",spr_KSW_Fish_ModelShip,spr_KSW_Fish_ModelShip_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,8000);
	scr_KSW_AddFish("Sun Ring","Kirby",spr_KSW_Fish_SunRing,spr_KSW_Fish_SunRing_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,8000);
	scr_KSW_AddFish("Wintertime","Kirby",spr_KSW_Fish_Wintertime,spr_KSW_Fish_Wintertime_Pal_Normal,legion,2,creamCrevasse,KSW_Phases.none,2500);
	scr_KSW_AddFish("Gold Watering Can","Animal Crossing",spr_KSW_Fish_GoldWateringCan,spr_KSW_Fish_GoldWateringCan_Pal_Normal,flux,2,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Katana","Kirby",spr_KSW_Fish_Katana,spr_KSW_Fish_Katana_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,9900);
	scr_KSW_AddFish("Charm","Kirby",spr_KSW_Fish_Charm,spr_KSW_Fish_Charm_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,8000);
	scr_KSW_AddFish("Xmas Tree","Kirby",spr_KSW_Fish_XmasTree,spr_KSW_Fish_XmasTree_Pal_Normal,mint,2,creamCrevasse,KSW_Phases.none,4000);
	scr_KSW_AddFish("Kong Barrel","Donkey Kong",spr_KSW_Fish_KongBarrel,spr_KSW_Fish_KongBarrel_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,1500);
	scr_KSW_AddFish("Ramia Scale","Kirby",spr_KSW_Fish_RamiaScale,spr_KSW_Fish_RamiaScale_Pal_Normal,mint,2,hallowReen,KSW_Phases.none,1280);
	scr_KSW_AddFish("Shiny Bamboo","Kirby",spr_KSW_Fish_ShinyBamboo,spr_KSW_Fish_ShinyBamboo_Pal_Normal,mint,2,grassBeach,KSW_Phases.none,6000);
	scr_KSW_AddFish("Tire","Kirby",spr_KSW_Fish_Tire,spr_KSW_Fish_Tire_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,1100);
	scr_KSW_AddFish("Spirit Charm","Kirby",spr_KSW_Fish_SpiritCharm,spr_KSW_Fish_SpiritCharm_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,7850);
	scr_KSW_AddFish("Pegasus Wing","Kirby",spr_KSW_Fish_PegasusWing,spr_KSW_Fish_PegasusWing_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,4280);
	scr_KSW_AddFish("Raccoon Doll","Kirby",spr_KSW_Fish_RaccoonDoll,spr_KSW_Fish_RaccoonDoll_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,8150);
	scr_KSW_AddFish("Shell Whistle","Kirby",spr_KSW_Fish_ShellWhistle,spr_KSW_Fish_ShellWhistle_Pal_Normal,mage,2,grassBeach,KSW_Phases.none,8200);
	scr_KSW_AddFish("Orichalcum","Kirby",spr_KSW_Fish_Orichalcum,spr_KSW_Fish_Orichalcum_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,5120);
	scr_KSW_AddFish("Platinum Ring","Kirby",spr_KSW_Fish_PlatinumRing,spr_KSW_Fish_PlatinumRing_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,4000);
	scr_KSW_AddFish("Triforce","Zelda",spr_KSW_Fish_Triforce,spr_KSW_Fish_Triforce_Pal_Normal,glimmer,2,grassBeach,KSW_Phases.none,8000);
	scr_KSW_AddFish("Crewmate","Among Us",spr_KSW_Fish_Crewmate,spr_KSW_Fish_Crewmate_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,6666);
	scr_KSW_AddFish("Super Mushroom","Mario",spr_KSW_Fish_SuperMushroom,spr_KSW_Fish_SuperMushroom_Pal_Normal,candy,2,grassBeach,KSW_Phases.none,2000);
	scr_KSW_AddFish("Soda","Kirby",spr_KSW_Fish_Soda,spr_KSW_Fish_Soda_Pal_Normal,legion,2,grassBeach,KSW_Phases.none,18000);
	scr_KSW_AddFish("Grape Soda","Kirby",spr_KSW_Fish_GrapeSoda,spr_KSW_Fish_GrapeSoda_Pal_Normal,flux,2,grassBeach,KSW_Phases.none,1800);
	scr_KSW_AddFish("Kirburger","Kirby",spr_KSW_Fish_Kirburger,spr_KSW_Fish_Kirburger_Pal_Normal,borange,2,grassBeach,KSW_Phases.none,5000);
	#endregion
	
	#region 1.1
	scr_KSW_AddFish("Small Silhouette Fish","Soft & Wet",spr_KSW_Fish_SmallSil,spr_KSW_Fish_Silhouette_Pal,legion,0,grassBeach,KSW_Phases.night,100);
	scr_KSW_AddFish("Silhouette Fish","Soft & Wet",spr_KSW_Fish_RegularSil,spr_KSW_Fish_Silhouette_Pal,legion,0,grassBeach,KSW_Phases.night,300);
	scr_KSW_AddFish("Big Silhouette Fish","Soft & Wet",spr_KSW_Fish_LargeSil,spr_KSW_Fish_Silhouette_Pal,legion,0,grassBeach,KSW_Phases.night,450);
	scr_KSW_AddFish("Wizzer","Kirby",spr_KSW_Fish_Wizzer,spr_KSW_Fish_Wizzer_Pal,legion,0,grassBeach,KSW_Phases.day,300,2);
	scr_KSW_AddFish("Rango","Gamble Galaxy\nStories",spr_KSW_Fish_Rango,spr_KSW_Fish_Rango_Pal,mage,0,grassBeach,KSW_Phases.day,400,-2,3);
	scr_KSW_AddFish("Fizzy","Gamble Galaxy\nStories",spr_KSW_Fish_Fizzy,spr_KSW_Fish_Fizzy_Pal,flux,0,grassBeach,KSW_Phases.day,300);
	scr_KSW_AddFish("Peeler","Gamble Galaxy\nStories",spr_KSW_Fish_Peeler,spr_KSW_Fish_Peeler_Pal,candy,0,grassBeach,KSW_Phases.day,400);
	scr_KSW_AddFish("Chubby Whale","Gamble Galaxy\nStories",spr_KSW_Fish_ChubbyWhale,spr_KSW_Fish_ChubbyWhale_Pal,borange,0,grassBeach,KSW_Phases.night,500,0,2);
	scr_KSW_AddFish("Prankler","Gamble Galaxy\nStories",spr_KSW_Fish_Prankler,spr_KSW_Fish_Prankler_Pal,legion,0,grassBeach,KSW_Phases.night,400,0,1);
	scr_KSW_AddFish("Stirfry","Gamble Galaxy\nStories",spr_KSW_Fish_Stirfry,spr_KSW_Fish_Stirfry_Pal,glimmer,1,grassBeach,KSW_Phases.afternoon,750,2,2);
	scr_KSW_AddFish("Nozzlor","Gamble Galaxy\nStories",spr_KSW_Fish_Nozzlor,spr_KSW_Fish_Nozzlor_Pal,mage,1,grassBeach,KSW_Phases.day,1200,-10);
	scr_KSW_AddFish("Blubby","Kirby's Dream\nLand 2 + 3",spr_KSW_FIsh_Blubby,spr_KSW_Fish_Blubby_Pal,candy,0,grassBeach,KSW_Phases.day,300,0,0,-1,snd_KSW_Bubble1);
	scr_KSW_AddFish("Sweet Stuff","Kirby",spr_KSW_Fish_SweetStuff,spr_KSW_Fish_SweetStuff_Pal,borange,2,grassBeach,KSW_Phases.afternoon,25000,-3,8);
	scr_KSW_AddFish("Azurill","Pokemon",spr_KSW_Fish_Azurill,spr_KSW_Fish_Azurill_Pal,mage,0,grassBeach,KSW_Phases.day,300);
	scr_KSW_AddFish("Marill","Pokemon",spr_KSW_Fish_Marill,spr_KSW_Fish_Marill_Pal,mage,1,grassBeach,KSW_Phases.day,1800);
	scr_KSW_AddFish("Azumarill","Pokemon",spr_KSW_Fish_Azumarill,spr_KSW_Fish_Azumarill_Pal,mage,2,grassBeach,KSW_Phases.day,6000);
	scr_KSW_AddFish("Totodile","Pokemon",spr_KSW_Fish_Totodile,spr_KSW_Fish_Totodile_Pal,legion,1,grassBeach,KSW_Phases.day,1200);
	scr_KSW_AddFish("Croconaw","Pokemon",spr_KSW_Fish_Croconaw,spr_KSW_Fish_Croconaw_Pal,legion,2,grassBeach,KSW_Phases.day,8500,-2);
	scr_KSW_AddFish("Feraligatr","Pokemon",spr_KSW_Fish_Feraligatr,spr_KSW_Fish_Feraligatr_Pal,legion,3,grassBeach,KSW_Phases.day,21000);
	scr_KSW_AddFish("Chinchou","Pokemon",spr_KSW_Fish_Chinchou,spr_KSW_Fish_Chinchou_Pal,glimmer,0,grassBeach,KSW_Phases.night,450);
	scr_KSW_AddFish("Lanturn","Pokemon",spr_KSW_Fish_Lanturn,spr_KSW_Fish_Lanturn_Pal,glimmer,1,grassBeach,KSW_Phases.night,2300,-2);
	scr_KSW_AddFish("Corsola","Pokemon",spr_KSW_Fish_Corsola,spr_KSW_Fish_Corsola_Pal,glimmer,1,grassBeach,KSW_Phases.afternoon,2400);
	scr_KSW_AddFish("Dunsparce","Pokemon",spr_KSW_Fish_Dunsparce,spr_KSW_Fish_Dunsparce_Pal,borange,3,grassBeach,KSW_Phases.day,200,-4);
	scr_KSW_AddFish("Mantyke","Pokemon",spr_KSW_Fish_Mantyke,spr_KSW_Fish_Mantyke_Pal,mage,1,grassBeach,KSW_Phases.afternoon,1000);
	scr_KSW_AddFish("Mantine","Pokemon",spr_KSW_Fish_Mantine,spr_KSW_Fish_Mantine_Pal,legion,2,grassBeach,KSW_Phases.afternoon,8000,0,-8);
	scr_KSW_AddFish("Qwilfish","Pokemon",spr_KSW_Fish_Qwilfish,spr_KSW_Fish_Qwilfish_Pal,flux,1,grassBeach,KSW_Phases.night,1800);
	scr_KSW_AddFish("Remoraid","Pokemon",spr_KSW_Fish_Remoraid,spr_KSW_Fish_Remoraid_Pal,candy,0,grassBeach,KSW_Phases.day,500,-1);
	scr_KSW_AddFish("Octillery","Pokemon",spr_KSW_Fish_Octillery,spr_KSW_Fish_Octillery_Pal,candy,1,grassBeach,KSW_Phases.day,3000,0,2);
	scr_KSW_AddFish("Wooper","Pokemon",spr_KSW_Fish_Wooper,spr_KSW_Fish_Wooper_Pal,mage,0,grassBeach,KSW_Phases.day,200);
	scr_KSW_AddFish("Quagsire","Pokemon",spr_KSW_Fish_Quagsire,spr_KSW_Fish_Quagsire_Pal,mage,1,grassBeach,KSW_Phases.day,2700,0,-2);
	scr_KSW_AddFish("Lugia","Pokemon",spr_KSW_Fish_Lugia,spr_KSW_Fish_Lugia_Pal,mage,3,creamCrevasse,KSW_Phases.none,35000,0,4);
	scr_KSW_AddFish("Barboach","Pokemon",spr_KSW_Fish_Barboach,spr_KSW_Fish_Barboach_Pal,legion,0,grassBeach,KSW_Phases.afternoon,400,-1,-2);
	scr_KSW_AddFish("Whiscash","Pokemon",spr_KSW_Fish_Whiscash,spr_KSW_Fish_Whiscash_Pal,legion,2,grassBeach,KSW_Phases.afternoon,9250,0,-2);
	scr_KSW_AddFish("Carvana","Pokemon",spr_KSW_Fish_Carvana,spr_KSW_Fish_Carvana_Pal,candy,0,grassBeach,KSW_Phases.night,650,0,-1);
	scr_KSW_AddFish("Sharpedo","Pokemon",spr_KSW_Fish_Sharpedo,spr_KSW_Fish_Sharpedo_Pal,flux,2,grassBeach,KSW_Phases.night,8750,-1,0);
	scr_KSW_AddFish("Clamperl","Pokemon",spr_KSW_Fish_Clamperl,spr_KSW_Fish_Clamperl_Pal,legion,1,grassBeach,KSW_Phases.day,1600);
	scr_KSW_AddFish("Huntail","Pokemon",spr_KSW_Fish_Huntail,spr_KSW_Fish_Huntail_Pal,mage,2,grassBeach,KSW_Phases.night,8500,-8);
	scr_KSW_AddFish("Gorebyss","Pokemon",spr_KSW_Fish_Gorebyss,spr_KSW_Fish_Gorebyss_Pal,glimmer,2,grassBeach,KSW_Phases.afternoon,8500,-8);
	scr_KSW_AddFish("Corphish","Pokemon",spr_KSW_Fish_Corphish,spr_KSW_Fish_Corphish_Pal,candy,1,grassBeach,KSW_Phases.day,1300);
	scr_KSW_AddFish("Crawdaunt","Pokemon",spr_KSW_Fish_Crawdaunt,spr_KSW_Fish_Crawdaunt_Pal,candy,2,grassBeach,KSW_Phases.night,9200,0,-1);
	scr_KSW_AddFish("Feebas","Pokemon",spr_KSW_Fish_Feebas,spr_KSW_Fish_Feebas_Pal,glimmer,0,grassBeach,KSW_Phases.day,100,-1);
	scr_KSW_AddFish("Milotic","Pokemon",spr_KSW_Fish_Milotic,spr_KSW_Fish_Milotic_Pal,glimmer,3,grassBeach,KSW_Phases.day,20500,-8,4);
	scr_KSW_AddFish("Lileep","Pokemon",spr_KSW_Fish_Lileep,spr_KSW_Fish_Lileep_Pal,mint,1,grassBeach,KSW_Phases.afternoon,2000);
	scr_KSW_AddFish("Cradily","Pokemon",spr_KSW_Fish_Cradily,spr_KSW_Fish_Cradily_Pal,mint,2,grassBeach,KSW_Phases.afternoon,9500);
	scr_KSW_AddFish("Luvdisc","Pokemon",spr_KSW_Fish_Luvdisc,spr_KSW_Fish_Luvdisc_Pal,glimmer,2,grassBeach,KSW_Phases.afternoon,5000);
	scr_KSW_AddFish("Mudkip","Pokemon",spr_KSW_Fish_Mudkip,spr_KSW_Fish_Mudkip_Pal,legion,1,grassBeach,KSW_Phases.afternoon,1550);
	scr_KSW_AddFish("Marshtomp","Pokemon",spr_KSW_Fish_Marshtomp,spr_KSW_Fish_Marshtomp_Pal,legion,2,grassBeach,KSW_Phases.afternoon,9800,1);
	scr_KSW_AddFish("Swampert","Pokemon",spr_KSW_Fish_Swampert,spr_KSW_Fish_Swampert_Pal,legion,3,grassBeach,KSW_Phases.afternoon,22050);
	scr_KSW_AddFish("Relicanth","Pokemon",spr_KSW_Fish_Relicanth,spr_KSW_Fish_Relicanth_Pal,borange,1,grassBeach,KSW_Phases.afternoon,2500,-3);
	scr_KSW_AddFish("Spheal","Pokemon",spr_KSW_Fish_Spheal,spr_KSW_Fish_Spheal_Pal,mage,0,grassBeach,KSW_Phases.day,600);
	scr_KSW_AddFish("Sealeo","Pokemon",spr_KSW_Fish_Sealeo,spr_KSW_Fish_Sealeo_Pal,mage,1,grassBeach,KSW_Phases.day,2400);
	scr_KSW_AddFish("Walrein","Pokemon",spr_KSW_Fish_Walrein,spr_KSW_Fish_Walrein_Pal,mage,2,grassBeach,KSW_Phases.day,8800);
	scr_KSW_AddFish("Wailmer","Pokemon",spr_KSW_Fish_Wailmer,spr_KSW_Fish_Wailmer_Pal,mage,1,grassBeach,KSW_Phases.day,4000);
	scr_KSW_AddFish("Wailord","Pokemon",spr_KSW_Fish_Wailord,spr_KSW_Fish_Wailord_Pal,mage,2,grassBeach,KSW_Phases.day,18000,-20,-8);
	scr_KSW_AddFish("Surskit","Pokemon",spr_KSW_Fish_Surskit,spr_KSW_Fish_Surskit_Pal,mint,0,grassBeach,KSW_Phases.day,100);
	scr_KSW_AddFish("Masquerain","Pokemon",spr_KSW_Fish_Masquerain,spr_KSW_Fish_Masquerain_Pal,mint,1,grassBeach,KSW_Phases.afternoon,1600);
	scr_KSW_AddFish("Wingull","Pokemon",spr_KSW_Fish_Wingull,spr_KSW_Fish_Wingull_Pal,glimmer,0,grassBeach,KSW_Phases.afternoon,400);
	scr_KSW_AddFish("Pelipper","Pokemon",spr_KSW_Fish_Pelipper,spr_KSW_Fish_Pelipper_Pal,glimmer,1,grassBeach,KSW_Phases.afternoon,2800,-1,-3);
	scr_KSW_AddFish("Kyogre","Pokemon",spr_KSW_Fish_Kyogre,spr_KSW_Fish_Kyogre_Pal,legion,3,grassBeach,KSW_Phases.day,50000,-12,5);
	scr_KSW_AddFish("Rayquaza","Pokemon",spr_KSW_Fish_Rayquaza,spr_KSW_Fish_Rayquaza_Pal,flux,3,grassBeach,KSW_Phases.afternoon,80000,-16,16);
	scr_KSW_AddFish("Bidoof","Pokemon",spr_KSW_Fish_Bidoof,spr_KSW_Fish_Bidoof_Pal,borange,0,grassBeach,KSW_Phases.day,750);
	scr_KSW_AddFish("Bibarel","Pokemon",spr_KSW_Fish_Bibarel,spr_KSW_Fish_Bibarel_Pal,borange,1,grassBeach,KSW_Phases.day,2100,0,-3);
	scr_KSW_AddFish("Finneon","Pokemon",spr_KSW_Fish_Finneon,spr_KSW_Fish_Finneon_Pal,flux,0,grassBeach,KSW_Phases.night,550,0,2);
	scr_KSW_AddFish("Lumineon","Pokemon",spr_KSW_Fish_Lumineon,spr_KSW_Fish_Lumineon_Pal,flux,1,grassBeach,KSW_Phases.night,2750);
	scr_KSW_AddFish("Piplup","Pokemon",spr_KSW_Fish_Piplup,spr_KSW_Fish_Piplup_Pal,mage,1,creamCrevasse,KSW_Phases.none,1400);
	scr_KSW_AddFish("Prinplup","Pokemon",spr_KSW_Fish_Prinplup,spr_KSW_Fish_Prinplup_Pal,legion,2,creamCrevasse,KSW_Phases.none,9200,-1);
	scr_KSW_AddFish("Empoleon","Pokemon",spr_KSW_Fish_Empoleon,spr_KSW_Fish_Empoleon_Pal,legion,3,creamCrevasse,KSW_Phases.none,21000,0,2);
	scr_KSW_AddFish("Shellos (West)","Pokemon",spr_KSW_Fish_Shellos_West,spr_KSW_Fish_Shellos_West_Pal,glimmer,0,grassBeach,KSW_Phases.afternoon,700);
	scr_KSW_AddFish("Shellos (East)","Pokemon",spr_KSW_Fish_Shellos_East,spr_KSW_Fish_Shellos_East_Pal,mint,1,grassBeach,KSW_Phases.afternoon,3200);
	scr_KSW_AddFish("Gastrodon (West)","Pokemon",spr_KSW_Fish_Gastrodon_West,spr_KSW_Fish_Gastrodon_West_Pal,glimmer,0,grassBeach,KSW_Phases.afternoon,700);
	scr_KSW_AddFish("Gastrodon (East)","Pokemon",spr_KSW_Fish_Gastrodon_East,spr_KSW_Fish_Gastrodon_East_Pal,mint,1,grassBeach,KSW_Phases.afternoon,3200);
	scr_KSW_AddFish("Phione","Pokemon",spr_KSW_Fish_Phione,spr_KSW_Fish_Phione_Pal,mage,3,creamCrevasse,KSW_Phases.none,21000,0,-1);
	scr_KSW_AddFish("Manaphy","Pokemon",spr_KSW_Fish_Manaphy,spr_KSW_Fish_Manaphy_Pal,legion,3,creamCrevasse,KSW_Phases.none,28000,-3);
	scr_KSW_AddFish("Forgotten Idol","Deirdre",spr_KSW_Fish_ForgottenIdol,spr_KSW_Fish_ForgottenIdol_Pal,flux,3,hallowReen,KSW_Phases.night,30000,0,6);
	scr_KSW_AddFish("Gezora","Godzilla",spr_KSW_Fish_Gezora,spr_KSW_Fish_Gezora_Pal,mage,1,grassBeach,KSW_Phases.day,3000,0,-18);
	scr_KSW_AddFish("Hedorah","Godzilla",spr_KSW_Fish_Hedorah,spr_KSW_Fish_Hedorah_Pal,flux,2,grassBeach,KSW_Phases.night,11500,0,20);
	scr_KSW_AddFish("Biollante Rose","Godzilla",spr_KSW_Fish_Biollante_Rose,spr_KSW_Fish_Biollante_Rose_Pal,mint,2,grassBeach,KSW_Phases.afternoon,10500,0,22);
	scr_KSW_AddFish("Biollante","Godzilla",spr_KSW_Fish_Biollante,spr_KSW_Fish_Biollante_Pal,mint,3,grassBeach,KSW_Phases.night,45000,-4,4);
	scr_KSW_AddFish("Varan","Godzilla",spr_KSW_Fish_Varan,spr_KSW_Fish_Varan_Pal,flux,3,grassBeach,KSW_Phases.afternoon,40000,-6,22);
	scr_KSW_AddFish("Goomdiver","Mario",spr_KSW_Fish_Goomdiver,spr_KSW_Fish_Goomdiver_Pal,borange,0,grassBeach,KSW_Phases.afternoon,500);
	scr_KSW_AddFish("Enguarde","Donkey Kong",spr_KSW_Fish_Enguarde,spr_KSW_Fish_Enguarde_Pal,legion,2,grassBeach,KSW_Phases.day,8000,-8,-6);
	scr_KSW_AddFish("Bitesize","Donkey Kong",spr_KSW_Fish_Bitesize,spr_KSW_Fish_Bitesize_Pal,flux,0,grassBeach,KSW_Phases.afternoon,600,-4);
	scr_KSW_AddFish("Chomps Jr.","Donkey Kong",spr_KSW_Fish_ChompsJr,spr_KSW_Fish_ChompsJr_Pal,mage,0,grassBeach,KSW_Phases.day,750,-14,-2);
	scr_KSW_AddFish("Chomps","Donkey Kong",spr_KSW_Fish_Chomps,spr_KSW_Fish_Chomps_Pal,mage,1,grassBeach,KSW_Phases.day,1900,-18,2);
	scr_KSW_AddFish("Croctopus","Donkey Kong",spr_KSW_Fish_Croctopus,spr_KSW_Fish_Croctopus_Pal,flux,1,grassBeach,KSW_Phases.night,1750,-8,2);
	scr_KSW_AddFish("Squidge","Donkey Kong",spr_KSW_Fish_Squidge,spr_KSW_Fish_Squidge_Pal,flux,1,grassBeach,KSW_Phases.night,1550);
	scr_KSW_AddFish("Clambo","Donkey Kong",spr_KSW_Fish_Clambo,spr_KSW_Fish_Clambo_Pal,candy,1,grassBeach,KSW_Phases.afternoon,5000);
	scr_KSW_AddFish("Glimmer","Donkey Kong",spr_KSW_Fish_Glimmer,spr_KSW_Fish_Glimmer_Pal,borange,1,grassBeach,KSW_Phases.night,3300,0,-2);
	scr_KSW_AddFish("Clapper","Donkey Kong",spr_KSW_Fish_Clapper,spr_KSW_Fish_Clapper_Pal,mint,2,grassBeach,KSW_Phases.afternoon,7500,-8,8);
	scr_KSW_AddFish("Flotsam","Donkey Kong",spr_KSW_Fish_Flotsam,spr_KSW_Fish_Flotsam_Pal,mage,0,grassBeach,KSW_Phases.day,720,-16,2);	
	scr_KSW_AddFish("Puftup","Donkey Kong",spr_KSW_Fish_Puftup,spr_KSW_Fish_Puftup_Pal,borange,0,grassBeach,KSW_Phases.day,680,-12,8);
	scr_KSW_AddFish("Lockjaw","Donkey Kong",spr_KSW_Fish_Lockjaw,spr_KSW_Fish_Lockjaw_Pal,candy,0,grassBeach,KSW_Phases.afternoon,900,-6);	
	scr_KSW_AddFish("Shuri","Donkey Kong",spr_KSW_Fish_Shuri,spr_KSW_Fish_Shuri_Pal,borange,1,grassBeach,KSW_Phases.afternoon,1700);
	scr_KSW_AddFish("Klaptrap","Donkey Kong",spr_KSW_Fish_Klaptrap,spr_KSW_Fish_Klaptrap_Pal,mage,0,grassBeach,KSW_Phases.day,800,-8);
	scr_KSW_AddFish("Kritter","Donkey Kong",spr_KSW_Fish_Kritter,spr_KSW_Fish_Kritter_Pal,mint,0,grassBeach,KSW_Phases.day,1000,-12,12);
	scr_KSW_AddFish("Krash","Donkey Kong",spr_KSW_Fish_Krash,spr_KSW_Fish_Krash_Pal,mint,1,grassBeach,KSW_Phases.night,2100,-12,16);
	scr_KSW_AddFish("Klump","Donkey Kong",spr_KSW_Fish_Klump,spr_KSW_Fish_Klump_Pal,mint,2,grassBeach,KSW_Phases.afternoon,7050,-6,16);
	scr_KSW_AddFish("Krusha","Donkey Kong",spr_KSW_Fish_Krusha,spr_KSW_Fish_Krusha_Pal,mint,2,grassBeach,KSW_Phases.day,6500,-8,16);
	scr_KSW_AddFish("Kudgel","Donkey Kong",spr_KSW_Fish_Kudgel,spr_KSW_Fish_Kudgel_Pal,flux,2,grassBeach,KSW_Phases.afternoon,9000,6,26);
	scr_KSW_AddFish("King K. Rool","Donkey Kong",spr_KSW_Fish_KingKRool,spr_KSW_Fish_KingKRool_Pal,mint,3,grassBeach,KSW_Phases.day,25000,0,22);
	scr_KSW_AddFish("Funky Kong","Donkey Kong",spr_KSW_Fish_FunkyKong,spr_KSW_Fish_FunkyKong_Pal,candy,3,grassBeach,KSW_Phases.day,22500,0,10);
	scr_KSW_AddFish("Duke Fishron","Terraria",spr_KSW_Fish_DukeFishron,spr_KSW_Fish_DukeFishron_Pal,mint,3,grassBeach,KSW_Phases.night,66666,-30,-2);
	scr_KSW_AddFish("Seadramon","Digimon",spr_KSW_Fish_Seadramon,spr_KSW_Fish_Seadramon_Pal,mage,2,grassBeach,KSW_Phases.day,10000,4,24);
	scr_KSW_AddFish("Trout Master Grimm","Hollow Knight",spr_KSW_Fish_TroutMasterGrimm,spr_KSW_Fish_TroutMasterGrimm_Pal,candy,3,hallowReen,KSW_Phases.none,100000,-2,30);
	scr_KSW_AddFish("Freezer","Saints Row",spr_KSW_Fish_Freezer,spr_KSW_Fish_Freezer_Pal,mage,2,creamCrevasse,KSW_Phases.none,7000,0,40);
	scr_KSW_AddFish("Strimpfish","Soft & Wet",spr_KSW_Fish_Strimpfish,spr_KSW_Fish_Strimpfish_Pal,legion,3,grassBeach,KSW_Phases.night,600000,-21,0,-1,snd_KSW_Fish_Strimpfish);
	scr_KSW_AddFish("King Fossil","Darius",spr_KSW_Fish_KingFossil,spr_KSW_Fish_KingFossil_Pal,legion,2,grassBeach,KSW_Phases.day,15000,-88,2);
	scr_KSW_AddFish("Great Thing","Darius",spr_KSW_Fish_GreatThing,spr_KSW_Fish_GreatThing_Pal,legion,3,grassBeach,KSW_Phases.night,100000,-52,-4);
	scr_KSW_AddFish("Moe","Starfy",spr_KSW_Fish_Moe,spr_KSW_Fish_Moe_Pal,borange,1,grassBeach,KSW_Phases.day,2500,-2,-2);
	scr_KSW_AddFish("Old Man Lobber","Starfy",spr_KSW_Fish_OldManLobber,spr_KSW_Fish_OldManLobber_Pal,candy,1,grassBeach,KSW_Phases.day,3200,-4);
	scr_KSW_AddFish("Starly","Starfy",spr_KSW_Fish_Starly,spr_KSW_Fish_Starly_Pal,glimmer,2,grassBeach,KSW_Phases.day,8900,-1,-3);
	scr_KSW_AddFish("Starfy","Starfy",spr_KSW_Fish_Starfy,spr_KSW_Fish_Starfy_Pal,mage,3,grassBeach,KSW_Phases.day,25000,0,-1);
	scr_KSW_AddFish("Mine","Crash Bandicoot",spr_KSW_Fish_Mine,spr_KSW_Fish_Mine_Pal,borange,0,grassBeach,KSW_Phases.none,1500);
	scr_KSW_AddFish("N. Trance","Crash Bandicoot",spr_KSW_Fish_NTrance,spr_KSW_Fish_NTrance_Pal,flux,2,grassBeach,KSW_Phases.afternoon,12500,-4,8);
	scr_KSW_AddFish("Crash Bandicoot","Crash Bandicoot",spr_KSW_Fish_CrashBandicoot,spr_KSW_Fish_CrashBandicoot_Pal,borange,3,grassBeach,KSW_Phases.afternoon,25000,-10,10);
	scr_KSW_AddFish("Dolphin","Mario",spr_KSW_Fish_Dolphin,spr_KSW_Fish_Dolphin_Pal,mage,1,grassBeach,KSW_Phases.day,2400,0,6);
	scr_KSW_AddFish("Urchin","Mario",spr_KSW_Fish_Urchin,spr_KSW_Fish_Urchin_Pal,legion,1,grassBeach,KSW_Phases.afternoon,2100);
	scr_KSW_AddFish("Porcu-Puffer","Mario",spr_KSW_Fish_Porcu_Puffer,spr_KSW_Fish_Porcu_Puffer_Pal,mage,2,grassBeach,KSW_Phases.day,5750,-6,6);
	scr_KSW_AddFish("Bumpty","Yoshi",spr_KSW_Fish_Bumpty,spr_KSW_Fish_Bumpty_Pal,legion,0,creamCrevasse,KSW_Phases.none,650);
	scr_KSW_AddFish("Hootie The Blue Fish","Yoshi",spr_KSW_Fish_HootieTheBlueFish,spr_KSW_Fish_HootieTheBlueFish_Pal,mage,0,grassBeach,KSW_Phases.day,620,-4);
	scr_KSW_AddFish("Clawdaddy","Yoshi",spr_KSW_Fish_Clawdaddy,spr_KSW_Fish_Clawdaddy_Pal,candy,1,grassBeach,KSW_Phases.afternoon,1900);
	scr_KSW_AddFish("Lunge Fish","Yoshi",spr_KSW_Fish_LungeFish,spr_KSW_Fish_LungeFish_Pal,legion,1,grassBeach,KSW_Phases.afternoon,2000,4,16);
	scr_KSW_AddFish("Prince Froggy","Yoshi",spr_KSW_Fish_PrinceFroggy,spr_KSW_Fish_PrinceFroggy_Pal,glimmer,2,grassBeach,KSW_Phases.afternoon,6000,-4,2);
	scr_KSW_AddFish("Hookbill The Koopa","Yoshi",spr_KSW_Fish_HookbillTheKoopa,spr_KSW_Fish_HookbillTheKoopa_Pal,candy,3,grassBeach,KSW_Phases.afternoon,9600,-24,24);
	scr_KSW_AddFish("Heavy Troopa","Mario",spr_KSW_Fish_HeavyTroopa,spr_KSW_Fish_HeavyTroopa_Pal,candy,3,grassBeach,KSW_Phases.afternoon,30000,-10,4);
	scr_KSW_AddFish("Balloon Eater","Balloon Fight",spr_KSW_Fish_BalloonEater,spr_KSW_Fish_BalloonEater_Pal,candy,1,grassBeach,KSW_Phases.night,3000,0,-2);
	scr_KSW_AddFish("Karlabos","Final Fantasy",spr_KSW_Fish_Karlabos,spr_KSW_Fish_Karlabos_Pal,candy,2,grassBeach,KSW_Phases.afternoon,7200,-14,-19);
	scr_KSW_AddFish("Adamantoise","Final Fantasy",spr_KSW_Fish_Adamantoise,spr_KSW_Fish_Adamantoise_Pal,legion,2,grassBeach,KSW_Phases.afternoon,12500,-4);
	scr_KSW_AddFish("Leviathan","Final Fantasy",spr_KSW_Fish_Leviathan,spr_KSW_Fish_Leviathan_Pal,mage,3,grassBeach,KSW_Phases.day,50000,-28,12);
	scr_KSW_AddFish("Toppin Cage","Pizza Tower",spr_KSW_Fish_ToppinCage,spr_KSW_Fish_ToppinCage_Pal,legion,1,grassBeach,KSW_Phases.day,1500,0,4);
	scr_KSW_AddFish("Mushroom Toppin","Pizza Tower",spr_KSW_Fish_MushroomToppin,spr_KSW_Fish_MushroomToppin_Pal,borange,1,grassBeach,KSW_Phases.day,1400,-1);
	scr_KSW_AddFish("Tomato Toppin","Pizza Tower",spr_KSW_Fish_TomatoToppin,spr_KSW_Fish_TomatoToppin_Pal,candy,1,grassBeach,KSW_Phases.day,1450,-5);
	scr_KSW_AddFish("Sausage Toppin","Pizza Tower",spr_KSW_Fish_SausageToppin,spr_KSW_Fish_SausageToppin_Pal,borange,1,grassBeach,KSW_Phases.day,1350,1);
	scr_KSW_AddFish("Pineapple Toppin","Pizza Tower",spr_KSW_Fish_PineappleToppin,spr_KSW_Fish_PineappleToppin_Pal,glimmer,1,grassBeach,KSW_Phases.day,1250,-1,4);
	scr_KSW_AddFish("Piraneapple","Pizza Tower",spr_KSW_Fish_Piraneapple,spr_KSW_Fish_Piraneapple_Pal,glimmer,1,grassBeach,KSW_Phases.day,2200,-16);
	scr_KSW_AddFish("The Doise","Pizza Tower",spr_KSW_Fish_TheDoise,spr_KSW_Fish_TheDoise_Pal,flux,3,hallowReen,KSW_Phases.none,18000,16,-2);
	scr_KSW_AddFish("Froggit","Undertale",spr_KSW_Fish_Froggit,spr_KSW_Fish_Froggit_Pal,mage,0,grassBeach,KSW_Phases.day,800);
	scr_KSW_AddFish("Aaron","Undertale",spr_KSW_Fish_Aaron,spr_KSW_Fish_Aaron_Pal,glimmer,1,grassBeach,KSW_Phases.day,2000,2,14);
	scr_KSW_AddFish("Woshua","Undertale",spr_KSW_Fish_Woshua,spr_KSW_Fish_Woshua_Pal,legion,1,grassBeach,KSW_Phases.night,2150);
	scr_KSW_AddFish("Shyren","Undertale",spr_KSW_Fish_Shyren,spr_KSW_Fish_Shyren_Pal,mage,1,grassBeach,KSW_Phases.night,2100);
	scr_KSW_AddFish("Onion-san","Undertale",spr_KSW_Fish_Onion_san,spr_KSW_Fish_Onion_san_Pal,borange,2,grassBeach,KSW_Phases.day,10000,1,-14);
	scr_KSW_AddFish("Undyne","Undertale",spr_KSW_Fish_Undyne,spr_KSW_Fish_Undyne_Pal,flux,3,grassBeach,KSW_Phases.day,27500,0,14);
	scr_KSW_AddFish("Cuptain","Deltarune",spr_KSW_Fish_Cuptain,spr_KSW_Fish_Cuptain_Pal,candy,0,grassBeach,KSW_Phases.day,600,-2,-6);
	scr_KSW_AddFish("Wobbly Thing","Deltarune",spr_KSW_Fish_WobblyThing,spr_KSW_Fish_WobblyThing_Pal,flux,1,grassBeach,KSW_Phases.night,1850,0,6);
	scr_KSW_AddFish("Water Cooler","Deltarune",spr_KSW_Fish_WaterCooler,spr_KSW_Fish_WaterCooler_Pal,mage,2,grassBeach,KSW_Phases.day,7500,4,8);
	scr_KSW_AddFish("Miss Mizzle","Deltarune",spr_KSW_Fish_MissMizzle,spr_KSW_Fish_MissMizzle_Pal,mage,2,grassBeach,KSW_Phases.day,10000,-22,12);
	var jack = scr_KSW_AddFish("YOUR TAKING TOO LONG","Deltarune",spr_KSW_Fish_Jackenstein,spr_KSW_Fish_Jackenstein_Pal,flux,3,hallowReen,KSW_Phases.none,25000,-18,8,-1,snd_KSW_Fish_TOOLONG);
	jack.displayedName = "[shake]YOUR TAKING TOO LONG[/shake]";
	scr_KSW_AddFish("Titan Spawn","[shake]Deltarune[/shake]",spr_KSW_Fish_TitanSpawn,spr_KSW_Fish_TitanSpawn_Pal,flux,3,hallowReen,KSW_Phases.night,22000,-6,2,-1,snd_KSW_Fish_TitanSpawn);
	var gaster = scr_KSW_AddFish("???","[blink]Undertale[/blink]",spr_KSW_Fish_Gaster,spr_KSW_Fish_Gaster_Pal,flux,3,grassBeach,KSW_Phases.none,66667,-1,10);
	gaster.displayedName = "[blink]??????[/blink]";
	var friend = scr_KSW_AddFish("DEVICE_FISH","Deltarune",spr_KSW_Fish_DeviceFish,spr_KSW_Fish_DeviceFish_Pal_Legend,glimmer,3,hallowReen,KSW_Phases.night,66667,-8,4,-1,snd_KSW_Fish_DeviceFish);
	//friend.displayedName = "[spr_KSW_UI_CatchPopup_MikeName_Small][/sprite]"
	scr_KSW_AddFish("Akmodan","Castlevania",spr_KSW_Fish_Akmodan,spr_KSW_Fish_Akmodan_Pal,borange,1,hallowReen,KSW_Phases.none,2200,2,22);
	scr_KSW_AddFish("Axe","Castlevania",spr_KSW_Fish_Axe,spr_KSW_Fish_Axe_Pal,flux,0,hallowReen,KSW_Phases.none,850);
	scr_KSW_AddFish("Bloodlines Count","Castlevania",spr_KSW_Fish_BloodlinesCount,spr_KSW_Fish_BloodlinesCount_Pal,legion,2,hallowReen,KSW_Phases.none,8250,-2,28);
	scr_KSW_AddFish("Boomerang","Castlevania",spr_KSW_Fish_Boomerang,spr_KSW_Fish_Boomerang_Pal,mage,0,hallowReen,KSW_Phases.none,750);
	scr_KSW_AddFish("Candle","Castlevania",spr_KSW_Fish_Candle,spr_KSW_Fish_Candle_Pal,candy,0,hallowReen,KSW_Phases.none,700);
	scr_KSW_AddFish("Carmilla","Castlevania",spr_KSW_Fish_Carmilla,spr_KSW_Fish_Carmilla_Pal,legion,1,hallowReen,KSW_Phases.none,2000,2);
	scr_KSW_AddFish("Classic Alucard","Castlevania",spr_KSW_Fish_ClassicAlucard,spr_KSW_Fish_ClassicAlucard_Pal,candy,1,hallowReen,KSW_Phases.none,2400,0,10);
	scr_KSW_AddFish("Classic Count","Castlevania",spr_KSW_Fish_ClassicCount,spr_KSW_Fish_ClassicCount_Pal,flux,1,hallowReen,KSW_Phases.none,4000,-4,20);
	scr_KSW_AddFish("Classic Death","Castlevania",spr_KSW_Fish_ClassicDeath,spr_KSW_Fish_ClassicDeath_Pal,flux,1,hallowReen,KSW_Phases.none,3800,0,16);
	scr_KSW_AddFish("Classic Simon","Castlevania",spr_KSW_Fish_ClassicSimon,spr_KSW_Fish_ClassicSimon_Pal,borange,1,hallowReen,KSW_Phases.none,4000,0,6);
	scr_KSW_AddFish("Classic Skull Knight","Castlevania",spr_KSW_Fish_ClassicSkullKnight,spr_KSW_Fish_ClassicSkullKnight_Pal,legion,0,hallowReen,KSW_Phases.none,900,0,12);
	scr_KSW_AddFish("Cross","Castlevania",spr_KSW_Fish_Cross,spr_KSW_Fish_Cross_Pal,mage,0,hallowReen,KSW_Phases.none,600);
	scr_KSW_AddFish("Crown","Castlevania",spr_KSW_Fish_Crown,spr_KSW_Fish_Crown_Pal,borange,0,hallowReen,KSW_Phases.none,1000);
	scr_KSW_AddFish("Cyclops","Castlevania",spr_KSW_Fish_Cyclops,spr_KSW_Fish_Cyclops_Pal,legion,1,hallowReen,KSW_Phases.none,1900,0,10);
	scr_KSW_AddFish("Dagger","Castlevania",spr_KSW_Fish_Dagger,spr_KSW_Fish_Dagger_Pal,legion,0,hallowReen,KSW_Phases.none,500);
	scr_KSW_AddFish("Dancing Specters","Castlevania",spr_KSW_Fish_DancingSpecters,spr_KSW_Fish_DancingSpecters_Pal,borange,1,hallowReen,KSW_Phases.none,2150,0,18);
	scr_KSW_AddFish("Dark Count","Castlevania",spr_KSW_Fish_DarkCount,spr_KSW_Fish_DarkCount_Pal,legion,1,hallowReen,KSW_Phases.none,3000,-6,10);
	scr_KSW_AddFish("Death","Castlevania",spr_KSW_Fish_Death,spr_KSW_Fish_Death_Pal,borange,0,hallowReen,KSW_Phases.none,1500,8,18);
	scr_KSW_AddFish("Double Shot","Castlevania",spr_KSW_Fish_DoubleShot,spr_KSW_Fish_DoubleShot_Pal,legion,0,hallowReen,KSW_Phases.none,222);
	scr_KSW_AddFish("Elizabeth Bartley","Castlevania",spr_KSW_Fish_ElizabethBartley,spr_KSW_Fish_ElizabethBartley_Pal,candy,1,hallowReen,KSW_Phases.none,1800,-3,12);
	scr_KSW_AddFish("Eric Lecarde","Castlevania",spr_KSW_Fish_EricLecarde,spr_KSW_Fish_EricLecarde_Pal,mint,1,hallowReen,KSW_Phases.none,1900,0,4);
	scr_KSW_AddFish("Fire Bomb","Castlevania",spr_KSW_Fish_FireBomb,spr_KSW_Fish_FireBomb_Pal,mage,0,hallowReen,KSW_Phases.none,650);
	scr_KSW_AddFish("Gaibon","Castlevania",spr_KSW_Fish_Gaibon,spr_KSW_Fish_Gaibon_Pal,legion,1,hallowReen,KSW_Phases.none,2800,-4,10);
	scr_KSW_AddFish("Giant Minotaur","Castlevania",spr_KSW_Fish_GiantMinotaur,spr_KSW_Fish_GiantMinotaur_Pal,candy,1,hallowReen,KSW_Phases.none,3000,8,22);
	scr_KSW_AddFish("Grant Danasty","Castlevania",spr_KSW_Fish_GrantDanasty,spr_KSW_Fish_GrantDanasty_Pal,candy,1,hallowReen,KSW_Phases.none,2400,-1,4);
	scr_KSW_AddFish("Invisibility Potion","Castlevania",spr_KSW_Fish_InvisibilityPotion,spr_KSW_Fish_InvisibilityPotion_Pal,borange,0,hallowReen,KSW_Phases.none,700);
	scr_KSW_AddFish("John Morris","Castlevania",spr_KSW_Fish_JohnMorris,spr_KSW_Fish_JohnMorris_Pal,borange,1,hallowReen,KSW_Phases.none,2050,0,12);
	scr_KSW_AddFish("Large Heart","Castlevania",spr_KSW_Fish_LargeHeart,spr_KSW_Fish_LargeHeart_Pal,candy,0,hallowReen,KSW_Phases.none,800);
	scr_KSW_AddFish("Magic Crystal","Castlevania",spr_KSW_Fish_MagicCrystal,spr_KSW_Fish_MagicCrystal_Pal,candy,0,hallowReen,KSW_Phases.none,950);
	scr_KSW_AddFish("Maria Renard","Castlevania",spr_KSW_Fish_MariaRenard,spr_KSW_Fish_MariaRenard_Pal,candy,1,hallowReen,KSW_Phases.none,2200,0,8);
	scr_KSW_AddFish("Moai","Castlevania",spr_KSW_Fish_Moai,spr_KSW_Fish_Moai_Pal,borange,0,hallowReen,KSW_Phases.none,920);
	scr_KSW_AddFish("Money Bag","Castlevania",spr_KSW_Fish_MoneyBag,spr_KSW_Fish_MoneyBag_Pal,glimmer,0,hallowReen,KSW_Phases.none,1200);
	scr_KSW_AddFish("Morning Star","Castlevania",spr_KSW_Fish_MorningStar,spr_KSW_Fish_MorningStar_Pal,candy,0,hallowReen,KSW_Phases.none,550);
	scr_KSW_AddFish("Nasty Grant","Castlevania",spr_KSW_Fish_NastyGrant,spr_KSW_Fish_NastyGrant_Pal,glimmer,1,hallowReen,KSW_Phases.none,2000,-4,6);
	scr_KSW_AddFish("Phantom Bat","Castlevania",spr_KSW_Fish_PhantomBat,spr_KSW_Fish_PhantomBat_Pal,candy,1,hallowReen,KSW_Phases.none,2500);
	scr_KSW_AddFish("Pork Chop","Castlevania",spr_KSW_Fish_PorkChop,spr_KSW_Fish_PorkChop_Pal,candy,0,hallowReen,KSW_Phases.none,800);
	scr_KSW_AddFish("Richter Belmont","Castlevania",spr_KSW_Fish_RichterBelmont,spr_KSW_Fish_RichterBelmont_Pal,mage,1,hallowReen,KSW_Phases.none,2900,0,12);
	scr_KSW_AddFish("Slogra","Castlevania",spr_KSW_Fish_Slogra,spr_KSW_Fish_Slogra_Pal,borange,1,hallowReen,KSW_Phases.none,2800,-10,16);
	scr_KSW_AddFish("Small Heart","Castlevania",spr_KSW_Fish_SmallHeart,spr_KSW_Fish_SmallHeart_Pal,candy,0,hallowReen,KSW_Phases.none,300);
	scr_KSW_AddFish("Soleil Belmont","Castlevania",spr_KSW_Fish_SoleilBelmont,spr_KSW_Fish_SoleilBelmont_Pal,legion,1,hallowReen,KSW_Phases.none,2300);
	scr_KSW_AddFish("Stopwatch","Castlevania",spr_KSW_Fish_Stopwatch,spr_KSW_Fish_Stopwatch_Pal,mage,0,hallowReen,KSW_Phases.none,550);
	scr_KSW_AddFish("Sypha Belnandes","Castlevania",spr_KSW_Fish_SyphaBelnandes,spr_KSW_Fish_SyphaBelnandes_Pal,mage,1,hallowReen,KSW_Phases.none,2150,0,8);
	scr_KSW_AddFish("Torchvania","Castlevania",spr_KSW_Fish_Torchvania,spr_KSW_Fish_Torchvania_Pal,mage,0,hallowReen,KSW_Phases.none,450,0,4);
	scr_KSW_AddFish("Treasure Chestvania","Castlevania",spr_KSW_Fish_TreasureChestvania,spr_KSW_Fish_TreasureChestvania_Pal,borange,0,hallowReen,KSW_Phases.none,1000);
	scr_KSW_AddFish("Trevor Belmont","Castlevania",spr_KSW_Fish_TrevorBelmont,spr_KSW_Fish_TrevorBelmont_Pal,borange,1,hallowReen,KSW_Phases.none,2800,0,6);
	scr_KSW_AddFish("Triple Shot","Castlevania",spr_KSW_Fish_TripleShot,spr_KSW_Fish_TripleShot_Pal,candy,0,hallowReen,KSW_Phases.none,333);
	scr_KSW_AddFish("Undead Count","Castlevania",spr_KSW_Fish_UndeadCount,spr_KSW_Fish_UndeadCount_Pal,legion,0,hallowReen,KSW_Phases.none,2800,0,34);
	scr_KSW_AddFish("Vampire Bat","Castlevania",spr_KSW_Fish_VampireBat,spr_KSW_Fish_VampireBat_Pal,candy,0,hallowReen,KSW_Phases.none,900);
	scr_KSW_AddFish("Zapf Bat","Castlevania",spr_KSW_Fish_ZapfBat,spr_KSW_Fish_ZapfBat_Pal,glimmer,1,hallowReen,KSW_Phases.none,2750,-4,16);
	scr_KSW_AddFish("Zombievania","Castlevania",spr_KSW_Fish_Zombievania,spr_KSW_Fish_Zombievania_Pal,flux,0,hallowReen,KSW_Phases.none,250,0,6);
	scr_KSW_AddFish("Dry Bones","Mario",spr_KSW_Fish_DryBones,spr_KSW_Fish_DryBones_Pal,mage,0,hallowReen,KSW_Phases.none,900);
	scr_KSW_AddFish("Bony Beetle","Mario",spr_KSW_Fish_BonyBeetle,spr_KSW_Fish_BonyBeetle_Pal,mage,0,hallowReen,KSW_Phases.none,750);
	scr_KSW_AddFish("Boo","Mario",spr_KSW_Fish_Boo,spr_KSW_Fish_Boo_Pal,glimmer,0,hallowReen,KSW_Phases.none,500,0,0,-1,snd_KSW_Fish_Boo);
	scr_KSW_AddFish("Silly Boo","Mario",spr_KSW_Fish_SillyBoo,spr_KSW_Fish_SillyBoo_Pal,candy,0,hallowReen,KSW_Phases.none,650,0,0,-1,snd_KSW_Fish_Boo);
	scr_KSW_AddFish("Smiling Boo","Mario",spr_KSW_Fish_SmilingBoo,spr_KSW_Fish_SmilingBoo_Pal,glimmer,0,hallowReen,KSW_Phases.none,700,0,0,-1,snd_KSW_Fish_Boo);
	scr_KSW_AddFish("Blocky Boo","Mario",spr_KSW_Fish_BlockyBoo,spr_KSW_Fish_BlockyBoo_Pal,mage,1,hallowReen,KSW_Phases.none,2300,0,0,-1,snd_KSW_Fish_Boo);
	scr_KSW_AddFish("Eerie","Mario",spr_KSW_Fish_Eerie,spr_KSW_Fish_Eerie_Pal,mage,0,hallowReen,KSW_Phases.none,800);
	scr_KSW_AddFish("Big Boo","Mario",spr_KSW_Fish_BigBoo,spr_KSW_Fish_BigBoo_Pal,mage,1,hallowReen,KSW_Phases.none,3000,0,0,-1,snd_KSW_Fish_BigBoo_Temp);
	scr_KSW_AddFish("Jean De Fillet","Mario",spr_KSW_Fish_JeanDeFillet,spr_KSW_Fish_JeanDeFillet_Pal,borange,1,hallowReen,KSW_Phases.none,1900);
	scr_KSW_AddFish("Boo Guy","Mario",spr_KSW_Fish_BooGuy,spr_KSW_Fish_BooGuy_Pal,legion,0,hallowReen,KSW_Phases.none,800);
	scr_KSW_AddFish("Lantern Ghost","Mario",spr_KSW_Fish_LanternGhost,spr_KSW_Fish_LanternGhost_Pal,glimmer,1,hallowReen,KSW_Phases.none,2000);
	scr_KSW_AddFish("Boolloon","Mario",spr_KSW_Fish_Boolloon,spr_KSW_Fish_Boolloon_Pal,mage,0,hallowReen,KSW_Phases.none,550,0,0,-1,snd_KSW_Fish_SmallBoo_Temp);
	scr_KSW_AddFish("Blindfold Boo","Mario",spr_KSW_Fish_BlindfoldBoo,spr_KSW_Fish_BlindfoldBoo_Pal,borange,0,hallowReen,KSW_Phases.none,900,0,0,-1,snd_KSW_Fish_Boo);
	scr_KSW_AddFish("Spook","Mario",spr_KSW_Fish_Spook,spr_KSW_Fish_Spook_Pal,borange,1,hallowReen,KSW_Phases.none,1700);
	scr_KSW_AddFish("Boo Blah","Mario",spr_KSW_Fish_BooBlah,spr_KSW_Fish_BooBlah_Pal,mage,0,hallowReen,KSW_Phases.none,1000);	
	scr_KSW_AddFish("King Boo","Mario",spr_KSW_Fish_KingBoo,spr_KSW_Fish_KingBoo_Pal,flux,3,hallowReen,KSW_Phases.none,25000,0,0,-1,snd_KSW_Fish_KingBoo);	
	scr_KSW_AddFish("Delibird","Pokemon",spr_KSW_Fish_Delibird,spr_KSW_Fish_Delibird_Pal,candy,3,creamCrevasse,KSW_Phases.none,5000);
	scr_KSW_AddFish("Stantler","Pokemon",spr_KSW_Fish_Stantler,spr_KSW_Fish_Stantler_Pal,glimmer,2,creamCrevasse,KSW_Phases.none,9000);
	scr_KSW_AddFish("Swinub","Pokemon",spr_KSW_Fish_Swinub,spr_KSW_Fish_Swinub_Pal,glimmer,1,creamCrevasse,KSW_Phases.none,1600);
	scr_KSW_AddFish("Piloswine","Pokemon",spr_KSW_Fish_Piloswine,spr_KSW_Fish_Piloswine_Pal,glimmer,2,creamCrevasse,KSW_Phases.none,8000);
	scr_KSW_AddFish("Mamoswine","Pokemon",spr_KSW_Fish_Mamoswine,spr_KSW_Fish_Mamoswine_Pal,glimmer,3,creamCrevasse,KSW_Phases.none,21000);
	scr_KSW_AddFish("Sneasel","Pokemon",spr_KSW_Fish_Sneasel,spr_KSW_Fish_Sneasel_Pal,flux,1,creamCrevasse,KSW_Phases.none,1900);
	scr_KSW_AddFish("Weavile","Pokemon",spr_KSW_Fish_Weavile,spr_KSW_Fish_Weavile_Pal,flux,2,creamCrevasse,KSW_Phases.none,9000);
	scr_KSW_AddFish("Snorunt","Pokemon",spr_KSW_Fish_Snorunt,spr_KSW_Fish_Snorunt_Pal,glimmer,1,creamCrevasse,KSW_Phases.none,1750);
	scr_KSW_AddFish("Glalie","Pokemon",spr_KSW_Fish_Glalie,spr_KSW_Fish_Glalie_Pal,legion,2,creamCrevasse,KSW_Phases.none,8500);
	scr_KSW_AddFish("Froslass","Pokemon",spr_KSW_Fish_Froslass,spr_KSW_Fish_Froslass_Pal,mage,2,creamCrevasse,KSW_Phases.none,8500);
	scr_KSW_AddFish("Regice","Pokemon",spr_KSW_Fish_Regice,spr_KSW_Fish_Regice_Pal,mage,3,creamCrevasse,KSW_Phases.none,25000);
	scr_KSW_AddFish("Snover","Pokemon",spr_KSW_Fish_Snover,spr_KSW_Fish_Snover_Pal,mage,1,creamCrevasse,KSW_Phases.none,1500);
	scr_KSW_AddFish("Abomasnow","Pokemon",spr_KSW_Fish_Abomasnow,spr_KSW_Fish_Abomasnow_Pal,legion,3,creamCrevasse,KSW_Phases.none,15000);
	scr_KSW_AddFish("Blorbsidian","Shovel Knight",spr_KSW_Fish_Blorbsidian,spr_KSW_Fish_Blorbsidian_Pal,mage,0,creamCrevasse,KSW_Phases.none,600);
	scr_KSW_AddFish("Spinwulf","Shovel Knight",spr_KSW_Fish_Spinwulf,spr_KSW_Fish_Spinwulf_Pal,flux,0,creamCrevasse,KSW_Phases.none,800);
	scr_KSW_AddFish("Icedrake","Shovel Knight",spr_KSW_Fish_Icedrake,spr_KSW_Fish_Icedrake_Pal,legion,0,creamCrevasse,KSW_Phases.none,1000,-10,2);
	scr_KSW_AddFish("Tundread","Shovel Knight",spr_KSW_Fish_Tundread,spr_KSW_Fish_Tundread_Pal,mage,1,creamCrevasse,KSW_Phases.none,2200,-2,2);
	scr_KSW_AddFish("Rungstrider","Shovel Knight",spr_KSW_Fish_Rungstrider,spr_KSW_Fish_Rungstrider_Pal,mage,1,creamCrevasse,KSW_Phases.none,2000,0,6);
	scr_KSW_AddFish("Hurlsvelgr","Shovel Knight",spr_KSW_Fish_Hurlsvelgr,spr_KSW_Fish_Hurlsvelgr_Pal,mage,2,creamCrevasse,KSW_Phases.none,8000,-36,24);
	scr_KSW_AddFish("Polar Knight","Shovel Knight",spr_KSW_Fish_PolarKnight,spr_KSW_Fish_PolarKnight_Pal,candy,3,creamCrevasse,KSW_Phases.none,24000,-12);
	scr_KSW_AddFish("Hermie III","Mario",spr_KSW_Fish_HermieIII,spr_KSW_Fish_HermieIII_Pal,candy,2,creamCrevasse,KSW_Phases.none,12500,-6,-14);
	scr_KSW_AddFish("Freeze Man","Mega Man",spr_KSW_Fish_FreezeMan,spr_KSW_Fish_FreezeMan_Pal,legion,1,creamCrevasse,KSW_Phases.none,4000,0,8);
	scr_KSW_AddFish("Frost Man","Mega Man",spr_KSW_Fish_FrostMan,spr_KSW_Fish_FrostMan_Pal,mage,2,creamCrevasse,KSW_Phases.none,8000,-12,-14,-1,snd_KSW_Fish_FrostMan);
	scr_KSW_AddFish("Cold Man","Mega Man",spr_KSW_Fish_ColdMan,spr_KSW_Fish_ColdMan_Pal,mage,1,creamCrevasse,KSW_Phases.none,3500,-8,8);
	scr_KSW_AddFish("Chill Penguin","Mega Man",spr_KSW_Fish_ChillPenguin,spr_KSW_Fish_ChillPenguin_Pal,legion,1,creamCrevasse,KSW_Phases.none,5000,-8,8);
	scr_KSW_AddFish("Blizzard Buffalo","Mega Man",spr_KSW_Fish_BlizzardBuffalo,spr_KSW_Fish_BlizzardBuffalo_Pal,glimmer,1,creamCrevasse,KSW_Phases.none,6000,-14);
	scr_KSW_AddFish("Frost Walrus","Mega Man",spr_KSW_Fish_FrostWalrus,spr_KSW_Fish_FrostWalrus_Pal,mage,2,creamCrevasse,KSW_Phases.none,7500,-14,12);
	scr_KSW_AddFish("Tidal Whale","Mega Man",spr_KSW_Fish_TidalWhale,spr_KSW_Fish_TidalWhale_Pal,legion,2,creamCrevasse,KSW_Phases.none,8500,-26,-4);
	scr_KSW_AddFish("Fairy Leviathan","Mega Man",spr_KSW_Fish_FairyLeviathan,spr_KSW_Fish_FairyLeviathan_Pal,legion,2,creamCrevasse,KSW_Phases.none,11000,0,8);
	scr_KSW_AddFish("A. Phen. Leviathan","Mega Man",spr_KSW_Fish_ArmedPhenomenonLeviathan,spr_KSW_Fish_ArmedPhenomenonLeviathan_Pal,legion,3,creamCrevasse,KSW_Phases.none,22000,-20,50);
	scr_KSW_AddFish("Blizzack Stagroff","Mega Man",spr_KSW_Fish_BlizzackStagroff,spr_KSW_Fish_BlizzackStagroff_Pal,mage,2,creamCrevasse,KSW_Phases.none,8000,-12);
	scr_KSW_AddFish("Fenri Lunaedge","Mega Man",spr_KSW_Fish_FenriLunaedge,spr_KSW_Fish_FenriLunaedge_Pal,mage,2,creamCrevasse,KSW_Phases.none,9500,-8,8);
	scr_KSW_AddFish("Lurerre","Mega Man",spr_KSW_Fish_Lurerre,spr_KSW_Fish_Lurerre_Pal,glimmer,1,creamCrevasse,KSW_Phases.none,4500,0,8);
	scr_KSW_AddFish("Chronoforce","Mega Man",spr_KSW_Fish_Chronoforce,spr_KSW_Fish_Chronoforce_Pal,legion,2,creamCrevasse,KSW_Phases.none,10000);
	scr_KSW_AddFish("M. Doomsday","Gamble Galaxy\nStories",spr_KSW_Fish_MDoomsday,spr_KSW_Fish_MDoomsday_Pal,borange,2,hallowReen,KSW_Phases.night,6666);
	scr_KSW_AddFish("Electoon","Rayman",spr_KSW_Fish_Electoon,spr_KSW_Fish_Electoon_Pal,candy,1,creamCrevasse,KSW_Phases.day,4000,0,3);
	scr_KSW_AddFish("Antitoon","Rayman",spr_KSW_Fish_Antitoon,spr_KSW_Fish_Antitoon_Pal,mage,1,creamCrevasse,KSW_Phases.night,4000,0,3);
	#endregion
	
	scr_KSW_AddFish("Grapes","Kirby",spr_KSW_Fish_Grapes,spr_KSW_Fish_Grapes_Pal_Normal,flux,0,grassBeach,KSW_Phases.none,50);
	
	#endregion
}